<a href="https://colab.research.google.com/github/Ebratul/Python/blob/main/pytorch/Dataset%26DataLoader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
! pip install opendatasets

Requirement already satisfied: opendatasets in /usr/local/lib/python3.12/dist-packages (0.1.22)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from opendatasets) (4.67.1)
Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (from opendatasets) (1.7.4.5)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from opendatasets) (8.3.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2026.1.4)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (3.4.4)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (5.29.5)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (0.5.1)

In [110]:
import opendatasets as od

In [111]:
od.download('https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data')

Skipping, found downloaded files in "./breast-cancer-wisconsin-data" (use force=True to force download)

In [112]:
import pandas as pd

In [113]:
df = pd.read_csv('/content/breast-cancer-wisconsin-data/data.csv')

In [114]:
df.sample(5)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
210,881046502,M,20.580,22.14,134.70,1290.0,0.09090,0.13480,0.16400,0.09561,0.1765,0.05024,0.8601,1.4800,7.029,111.70,0.008124,0.03611,0.05489,0.027650,0.03176,0.002365,23.24,27.84,158.30,1656.0,0.11780,0.2920,0.38610,0.19200,0.2909,0.05865,NaN
45,857010,M,18.650,17.60,123.70,1076.0,0.10990,0.16860,0.19740,0.10090,0.1907,0.06049,0.6289,0.6633,4.293,71.56,0.006294,0.03994,0.05554,0.016950,0.02428,0.003535,22.82,21.32,150.60,1567.0,0.16790,0.5090,0.73450,0.23780,0.3799,0.09185,NaN
416,905978,B,9.405,21.70,59.60,271.2,0.10440,0.06159,0.02047,0.01257,0.2025,0.06601,0.4302,2.8780,2.759,25.17,0.014740,0.01674,0.01367,0.008674,0.03044,0.004590,10.85,31.24,68.73,359.4,0.15260,0.1193,0.06141,0.03770,0.2872,0.08304,NaN
324,89511501,B,12.200,15.21,78.01,457.9,0.08673,0.06545,0.01994,0.01692,0.1638,0.06129,0.2575,0.8073,1.959,19.01,0.005403,0.01418,0.01051,0.005142,0.01333,0.002065,13.75,21.38,91.11,583.1,0.12560,0.1928,0.11670,0.05556,0.2661,0.07961,NaN
197,877159,M,18.080,21.84,117.40,1024.0,0.07371,0.08642,0.11030,0.05778,0.1770,0.05340,0.6362,1.3050,4.312,76.36,0.005530,0.05296,0.06110,0.014440,0.02140,0.005036,19.76,24.70,129.10,1228.0,0.08822,0.1963,0.25350,0.09181,0.2369,0.06558,NaN

In [115]:
df.shape

(569, 33)

In [116]:
df.drop(columns=['Unnamed: 32', 'id'], inplace = True)

In [117]:
pd.set_option('display.max_columns', None)
df.sample(5)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
567,M,20.60,29.33,140.10,1265.0,0.1178,0.27700,0.35140,0.15200,0.2397,0.07016,0.7260,1.5950,5.772,86.22,0.006522,0.061580,0.07117,0.016640,0.02324,0.006185,25.74,39.42,184.60,1821.0,0.1650,0.8681,0.93870,0.26500,0.4087,0.12400
303,B,10.49,18.61,66.86,334.3,0.1068,0.06678,0.02297,0.01780,0.1482,0.06600,0.1485,1.5630,1.035,10.08,0.008875,0.009362,0.01808,0.009199,0.01791,0.003317,11.06,24.54,70.76,375.4,0.1413,0.1044,0.08423,0.06528,0.2213,0.07842
528,B,13.94,13.17,90.31,594.2,0.1248,0.09755,0.10100,0.06615,0.1976,0.06457,0.5461,2.6350,4.091,44.74,0.010040,0.032470,0.04763,0.028530,0.01715,0.005528,14.62,15.38,94.52,653.3,0.1394,0.1364,0.15590,0.10150,0.2160,0.07253
22,M,15.34,14.26,102.50,704.4,0.1073,0.21350,0.20770,0.09756,0.2521,0.07032,0.4388,0.7096,3.384,44.91,0.006789,0.053280,0.06446,0.022520,0.03672,0.004394,18.07,19.08,125.10,980.9,0.1390,0.5954,0.63050,0.23930,0.4667,0.09946
353,M,15.08,25.74,98.00,716.6,0.1024,0.09769,0.12350,0.06553,0.1647,0.06464,0.6534,1.5060,4.174,63.37,0.010520,0.024310,0.04912,0.017460,0.02120,0.004867,18.51,33.22,121.20,1050.0,0.1660,0.2356,0.40290,0.15260,0.2654,0.09438

In [118]:
X = df.iloc[:,1:]
y = df.iloc[:,0]

In [119]:
X

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,1.1760,1.2560,7.673,158.70,0.010300,0.02891,0.05198,0.02454,0.01114,0.004239,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,0.7655,2.4630,5.203,99.04,0.005769,0.02423,0.03950,0.01678,0.01898,0.002498,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,0.4564,1.0750,3.425,48.55,0.005903,0.03731,0.04730,0.01557,0.01318,0.003892,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,0.7260,1.5950,5.772,86.22,0.006522,0.06158,0.07117,0.01664,0.02324,0.006185,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,0.3857,1.4280,2.548,19.15,0.007189,0.00466,0.00000,0.00000,0.02676,0.002783,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [120]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [121]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [122]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [123]:
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.transform(y_test)

In [124]:
import torch
import numpy as np

In [125]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [126]:
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
import torch.optim as optim

In [127]:
class CustomDataset(Dataset):

  def __init__(self, feature, labels):

    self.feature = feature
    self.labels = labels

  def __len__(self):
    return len(self.feature)

  def __getitem__(self, idx):
    return self.feature[idx], self.labels[idx]

In [128]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [129]:
train_dataset[1]

(tensor([-0.8607,  0.7434, -0.8522, -0.7921, -0.0444, -0.4253, -0.5053, -0.6787,
          0.8076,  0.3769, -0.4487,  0.4545, -0.4267, -0.4842, -1.1320,  0.2676,
          0.0774, -0.2364,  1.0709,  0.3101, -0.8830,  0.4479, -0.8793, -0.7782,
         -1.0119, -0.4877, -0.5541, -0.7577,  0.4393, -0.2223]),
 tensor(0.))

In [130]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [131]:
class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, feature):
    out = self.linear(feature)
    out = self.sigmoid(out)

    return out

In [132]:
learning_rate = 0.1
epoch = 500

In [133]:
model = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

loss_function = nn.BCELoss()

In [135]:
for epoch in range(epoch):
  for batch_feature, batch_label in train_loader:
    y_pred = model(batch_feature)

    loss = loss_function(y_pred, batch_label.view(-1,1))

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()
  if epoch % 50 == 0:
    print(f'Epoch: {epoch+1}, loss: {loss.item()}')

Epoch: 1, loss: 0.1836269646883011
Epoch: 51, loss: 0.00168695452157408
Epoch: 101, loss: 0.05589229613542557
Epoch: 151, loss: 0.03375149145722389
Epoch: 201, loss: 0.0009491864475421607
Epoch: 251, loss: 0.022323813289403915
Epoch: 301, loss: 0.0016348951030522585
Epoch: 351, loss: 0.013590085320174694
Epoch: 401, loss: 0.00035272398963570595
Epoch: 451, loss: 0.004272382706403732

In [136]:
model.eval()
accuracy_list = []

with torch.no_grad():
  for batch_feature, batch_label in test_loader:
    y_pred = model(batch_feature)
    y_pred = (y_pred > 0.8).float()

    batch_accuracy = (y_pred == batch_label.view(-1,1)).float().mean()
    accuracy_list.append(batch_accuracy)

overall_accuracy = sum(accuracy_list)/len(accuracy_list)
print(f'Overall accuracy: {overall_accuracy}')

Overall accuracy: 0.984375