<a href="https://colab.research.google.com/github/Ebratul/Python/blob/main/pytorch/PyTorch(4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install opendatasets

Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from opendatasets) (4.67.1)
Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (from opendatasets) (1.7.4.5)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from opendatasets) (8.3.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2026.1.4)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (3.4.4)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (5.29.5)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (0.5.1)
Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [2]:
import opendatasets as od

In [3]:
od.download('https://www.kaggle.com/datasets/yasserh/breast-cancer-dataset')

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: g65ashaharier21031
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/yasserh/breast-cancer-dataset
Downloading breast-cancer-dataset.zip to ./breast-cancer-dataset

100%|██████████| 48.6k/48.6k [00:00<00:00, 120MB/s]

In [4]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [5]:
df = pd.read_csv('/content/breast-cancer-dataset/breast-cancer.csv')

In [6]:
df.head(5)

         id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0    842302         M  ...          0.4601                  0.11890
1    842517         M  ...          0.2750                  0.08902
2  84300903         M  ...          0.3613                  0.08758
3  84348301         M  ...          0.6638                  0.17300
4  84358402         M  ...          0.2364                  0.07678

[5 rows x 32 columns]

In [7]:
df.shape

(569, 32)

In [8]:
df.drop(columns=['id'], inplace = True)

In [9]:
df.shape

(569, 31)

In [22]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [24]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [25]:
y_train

10     M
148    B
483    B
470    B
478    B
      ..
456    B
311    B
472    B
172    M
198    M
Name: diagnosis, Length: 455, dtype: object

In [27]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [28]:
y_train

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1])

In [30]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [35]:
X_train_tensor.shape

torch.Size([455, 30])

In [33]:
X_train

array([[ 0.53860868,  0.9235113 ,  0.43995459, ..., -0.22503267,
         0.07869222,  0.01679734],
       [ 0.0936535 , -1.01629934,  0.08454884, ...,  0.69356121,
        -0.35431682, -0.41628103],
       [-0.11474323, -0.42424796, -0.16826556, ..., -0.3621727 ,
        -0.64579762, -0.82345354],
       ...,
       [ 0.22882976, -1.07646717,  0.18551175, ...,  0.00327953,
        -0.3593714 , -0.08401024],
       [ 0.38090305, -1.80810791,  0.43181242, ...,  1.0417564 ,
         0.53023473,  0.94490287],
       [ 1.42851903,  0.74300783,  1.44958375, ...,  0.86002294,
         0.49148295,  0.44987571]])

In [34]:
y_train_tensor.shape

torch.Size([455])

In [47]:
class MySimpleNN():

  def __init__(self, X):
    self.weight = torch.rand(X.shape[1], 1, dtype = torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)


  def forward(self, X):
    z = torch.matmul(X, self.weight) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
    loss = -(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred))
    return loss.mean()

In [38]:
learning_rate = 0.01
epochs = 25

In [48]:
model = MySimpleNN(X_train_tensor)

for epoch in range(epochs):
  y_pred = model.forward(X_train_tensor)
  loss = model.loss_function(y_pred, y_train_tensor)
  loss.backward()

  with torch.no_grad():
    model.weight -= learning_rate * model.weight.grad
    model.bias -= learning_rate * model.bias.grad

  model.weight.grad.zero_()
  model.bias.grad.zero_()

  print(f"Epoch: {epoch+1} , Loss : {loss.item()}")

Epoch: 1 , Loss : 3.2465405548451387
Epoch: 2 , Loss : 3.2335487650006964
Epoch: 3 , Loss : 3.2205338508996975
Epoch: 4 , Loss : 3.20738805616583
Epoch: 5 , Loss : 3.194259703111973
Epoch: 6 , Loss : 3.1810912660530475
Epoch: 7 , Loss : 3.1677717042703306
Epoch: 8 , Loss : 3.1544708128531482
Epoch: 9 , Loss : 3.1411888955570166
Epoch: 10 , Loss : 3.127926258927681
Epoch: 11 , Loss : 3.114683212226212
Epoch: 12 , Loss : 3.1013908216436774
Epoch: 13 , Loss : 3.087980318353051
Epoch: 14 , Loss : 3.074590589268369
Epoch: 15 , Loss : 3.0612219603625213
Epoch: 16 , Loss : 3.047874760003668
Epoch: 17 , Loss : 3.0343070766176914
Epoch: 18 , Loss : 3.0202712323176417
Epoch: 19 , Loss : 3.006149351975183
Epoch: 20 , Loss : 2.9919358381971155
Epoch: 21 , Loss : 2.9777470910965027
Epoch: 22 , Loss : 2.9635834917479467
Epoch: 23 , Loss : 2.949445423576597
Epoch: 24 , Loss : 2.935156574692183
Epoch: 25 , Loss : 2.920506977757892

In [49]:
model.weight

tensor([[ 0.6701],
        [ 0.9075],
        [ 0.2613],
        [ 0.0502],
        [ 0.0172],
        [ 0.9182],
        [ 0.5986],
        [-0.0281],
        [ 0.1347],
        [ 0.3768],
        [ 0.4818],
        [ 0.5356],
        [ 0.6491],
        [ 0.1327],
        [ 0.2097],
        [ 0.2173],
        [ 0.5486],
        [-0.0169],
        [ 0.7660],
        [ 0.1627],
        [ 0.3945],
        [ 0.5511],
        [ 0.6905],
        [ 0.3720],
        [ 0.1005],
        [ 0.0848],
        [ 0.4353],
        [ 0.4984],
        [ 0.7226],
        [ 0.4038]], dtype=torch.float64, requires_grad=True)

In [50]:
model.bias

tensor([-0.0013], dtype=torch.float64, requires_grad=True)

In [54]:
with torch.no_grad():

  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')

Accuracy: 0.5473992228507996