<a href="https://colab.research.google.com/github/Ebratul/Python/blob/main/pytorch/PyTorch(4)_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
!pip install opendatasets

Requirement already satisfied: opendatasets in /usr/local/lib/python3.12/dist-packages (0.1.22)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from opendatasets) (4.67.1)
Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (from opendatasets) (1.7.4.5)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from opendatasets) (8.3.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2026.1.4)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (3.4.4)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (5.29.5)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (0.5.1)

In [73]:
import opendatasets as od

In [74]:
od.download('https://www.kaggle.com/datasets/yasserh/breast-cancer-dataset')

Skipping, found downloaded files in "./breast-cancer-dataset" (use force=True to force download)

In [75]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [76]:
df = pd.read_csv('/content/breast-cancer-dataset/breast-cancer.csv')

In [77]:
df.head(5)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [78]:
df.shape

(569, 32)

In [79]:
df.drop(columns=['id'], inplace = True)

In [80]:
df.shape

(569, 31)

In [81]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [82]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [83]:
y_train

472    B
399    B
293    B
497    B
35     M
      ..
543    B
496    B
170    B
316    B
342    B
Name: diagnosis, Length: 455, dtype: object

In [84]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [85]:
y_train

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [86]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [87]:
X_train_tensor.shape

torch.Size([455, 30])

In [88]:
X_train

array([[ 0.24415024, -0.97788885,  0.2056314 , ...,  0.01213893,
        -0.34112197, -0.02419274],
       [-0.66495795, -0.44064214, -0.69030638, ..., -0.92910231,
        -0.19646507, -0.11450741],
       [-0.65038891, -0.39452654, -0.67846766, ..., -0.34656112,
         0.31539781, -0.77641892],
       ...,
       [-0.51343992, -1.56355694, -0.53851702, ..., -0.30792004,
        -0.12016253, -0.91664433],
       [-0.55423323, -1.17388014, -0.60616687, ..., -1.46853792,
        -0.9690283 , -1.35276915],
       [-0.88057976, -0.97097151, -0.84970635, ..., -0.09870401,
         0.63332507,  0.45530689]])

In [89]:
y_train_tensor.shape

torch.Size([455])

In [90]:
import torch.nn as nn

In [91]:
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()

In [92]:
# class MySimpleNN(nn.Module):

#   def __init__(self, num_feature):
#     super().__init__()
#     self.linear1 = nn.Linear(num_feature, 10)
#     self.relu = nn.ReLU()
#     self.linear2 = nn.Linear(10, 1)
#     self.sigmoid = nn.Sigmoid()

#   def forward(self, feature):
#     out = self.linear1(feature)
#     out = self.relu(out)
#     out = self.linear2(out)
#     out = self.sigmoid(out)
#     return out

In [93]:
import torch
import torch.nn as nn

class MySimpleNN(nn.Module):

    def __init__(self, num_feature):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_feature, 10),
            nn.ReLU(),
            nn.Linear(10, 1),
            nn.Sigmoid()
        )

    def forward(self, feature):
        return self.network(feature)

In [94]:
learning_rate = 0.01
epochs = 25

In [95]:
X_train_tensor = X_train_tensor.float()
X_test_tensor  = X_test_tensor.float()
y_train_tensor = y_train_tensor.float()
y_test_tensor  = y_test_tensor.float()

In [96]:
model = MySimpleNN(X_train_tensor.shape[1])
model(X_test_tensor)

tensor([[0.6972],
        [0.5666],
        [0.5107],
        [0.5047],
        [0.5265],
        [0.5364],
        [0.5679],
        [0.4891],
        [0.6817],
        [0.5496],
        [0.5047],
        [0.4803],
        [0.5130],
        [0.4802],
        [0.4783],
        [0.4874],
        [0.4254],
        [0.5206],
        [0.5220],
        [0.5316],
        [0.4925],
        [0.5652],
        [0.5083],
        [0.5813],
        [0.4413],
        [0.4668],
        [0.5467],
        [0.4838],
        [0.4928],
        [0.5698],
        [0.4684],
        [0.5003],
        [0.4831],
        [0.5690],
        [0.4689],
        [0.5142],
        [0.4875],
        [0.5191],
        [0.5537],
        [0.5409],
        [0.5177],
        [0.4835],
        [0.5186],
        [0.5138],
        [0.5641],
        [0.4939],
        [0.3868],
        [0.4969],
        [0.5531],
        [0.4349],
        [0.5149],
        [0.5477],
        [0.5242],
        [0.4848],
        [0.5665],
        [0.5445],
        [0.5177],
        [0.4873],
        [0.4427],
        [0.5323],
        [0.4903],
        [0.4831],
        [0.4946],
        [0.4511],
        [0.5905],
        [0.5049],
        [0.5086],
        [0.5782],
        [0.5156],
        [0.5292],
        [0.5745],
        [0.5475],
        [0.4842],
        [0.5325],
        [0.5121],
        [0.5946],
        [0.4253],
        [0.5304],
        [0.4978],
        [0.4697],
        [0.5318],
        [0.4785],
        [0.5534],
        [0.5162],
        [0.5346],
        [0.5640],
        [0.5600],
        [0.5527],
        [0.5352],
        [0.3892],
        [0.5544],
        [0.5306],
        [0.4798],
        [0.4393],
        [0.4670],
        [0.6870],
        [0.5200],
        [0.5117],
        [0.5037],
        [0.5252],
        [0.5273],
        [0.4413],
        [0.4975],
        [0.3679],
        [0.4824],
        [0.5274],
        [0.5556],
        [0.4858],
        [0.5323],
        [0.4844],
        [0.5034],
        [0.5121],
        [0.5076],
        [0.5324]], grad_fn=<SigmoidBackward0>)

In [97]:
# First Linear Layer (input → hidden)
print("Layer 1 weights:", model.network[0].weight[0])
print("Layer 1 bias:", model.network[0].bias)

Layer 1 weights: tensor([ 0.1442, -0.1046,  0.1594, -0.1374, -0.1270, -0.0164, -0.0565, -0.1246,
        -0.0519,  0.0928,  0.1162, -0.0625,  0.0955,  0.1146,  0.0109, -0.1231,
         0.1629, -0.0122, -0.1636, -0.1247, -0.0608, -0.0829,  0.1750, -0.0236,
         0.1012,  0.1560,  0.0173,  0.1357, -0.0132, -0.1220],
       grad_fn=<SelectBackward0>)
Layer 1 bias: Parameter containing:
tensor([ 0.0218,  0.1297,  0.0400, -0.0240,  0.1742, -0.0563, -0.0634,  0.0533,
        -0.0878, -0.1508], requires_grad=True)

In [98]:
model.network[0].bias

Parameter containing:
tensor([ 0.0218,  0.1297,  0.0400, -0.0240,  0.1742, -0.0563, -0.0634,  0.0533,
        -0.0878, -0.1508], requires_grad=True)

In [99]:
# Second Linear Layer (hidden → output)
print("Layer 2 weights:", model.network[2].weight)
print("Layer 2 bias:", model.network[2].bias)

Layer 2 weights: Parameter containing:
tensor([[-0.0921,  0.3119, -0.0741, -0.2171,  0.2554, -0.1199, -0.0630,  0.0892,
          0.0866,  0.1718]], requires_grad=True)
Layer 2 bias: Parameter containing:
tensor([-0.0829], requires_grad=True)

In [100]:
with torch.no_grad():
    y_pred = model(X_test_tensor)   # forward() এখন কাজ করবে
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.47922438383102417

In [101]:
!pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

In [102]:
from torchinfo import summary

In [104]:
summary(model, input_size=X_train_tensor.shape)

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [455, 1]                  --
├─Sequential: 1-1                        [455, 1]                  --
│    └─Linear: 2-1                       [455, 10]                 310
│    └─ReLU: 2-2                         [455, 10]                 --
│    └─Linear: 2-3                       [455, 1]                  11
│    └─Sigmoid: 2-4                      [455, 1]                  --
==========================================================================================
Total params: 321
Trainable params: 321
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.15
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.04
Params size (MB): 0.00
Estimated Total Size (MB): 0.10
==========================================================================================

In [105]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [106]:
import torch.nn as nn

In [116]:

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [117]:
learning_rate = 0.1
epochs = 25

In [118]:
loss_function = nn.BCELoss()

In [119]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [120]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.614974319934845
Epoch: 2, Loss: 0.48629823327064514
Epoch: 3, Loss: 0.41658321022987366
Epoch: 4, Loss: 0.37197011709213257
Epoch: 5, Loss: 0.3403448760509491
Epoch: 6, Loss: 0.3164147138595581
Epoch: 7, Loss: 0.29747673869132996
Epoch: 8, Loss: 0.2819925844669342
Epoch: 9, Loss: 0.26901495456695557
Epoch: 10, Loss: 0.2579251229763031
Epoch: 11, Loss: 0.24829959869384766
Epoch: 12, Loss: 0.23983757197856903
Epoch: 13, Loss: 0.2323186844587326
Epoch: 14, Loss: 0.22557732462882996
Epoch: 15, Loss: 0.2194862961769104
Epoch: 16, Loss: 0.21394607424736023
Epoch: 17, Loss: 0.2088773548603058
Epoch: 18, Loss: 0.20421622693538666
Epoch: 19, Loss: 0.1999104619026184
Epoch: 20, Loss: 0.1959168016910553
Epoch: 21, Loss: 0.19219917058944702
Epoch: 22, Loss: 0.18872714042663574
Epoch: 23, Loss: 0.18547485768795013
Epoch: 24, Loss: 0.18242017924785614
Epoch: 25, Loss: 0.17954400181770325

In [121]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5069252252578735