<a href="https://colab.research.google.com/github/Ebratul/Python/blob/main/Olympic/All_time_Olympic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [149]:
import numpy as np
import pandas as pd

In [150]:
df = pd.read_csv('/content/sample_data/athlete_events.csv')
region_df = pd.read_csv('/content/sample_data/noc_regions.csv')

In [151]:
df.sample(5)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
14602,7866,Yury Viktorovich Barinov,M,25.0,173.0,71.0,Soviet Union,URS,1980 Summer,1980,Summer,Moskva,Cycling,"Cycling Men's Road Race, Individual",Bronze
269712,134962,Wiesaw Ziemianin,M,31.0,183.0,90.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Biathlon,Biathlon Men's 20 kilometres,NaN
14141,7634,Philippe Baradel,M,30.0,165.0,67.0,France,FRA,1968 Winter,1968,Winter,Grenoble,Cross Country Skiing,Cross Country Skiing Men's 30 kilometres,NaN
195930,98385,Abdelmalek Rahou,M,26.0,180.0,NaN,Algeria,ALG,2012 Summer,2012,Summer,London,Boxing,Boxing Men's Middleweight,NaN
54021,27711,Gaspard Deridder,M,18.0,NaN,NaN,Belgium,BEL,1936 Summer,1936,Summer,Berlin,Boxing,Boxing Men's Welterweight,NaN

In [152]:
df.shape

(271116, 15)

In [153]:
df['Season'].value_counts()

Season
Summer    222552
Winter     48564
Name: count, dtype: int64

In [154]:
df = df[df['Season'] == 'Summer']
df.sample(5)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
250177,125309,Csongor Vargha,M,26.0,179.0,78.0,Hungary,HUN,1972 Summer,1972,Summer,Munich,Canoeing,"Canoeing Men's Kayak Fours, 1,000 metres",NaN
28021,14516,Ann Patricia Mary Bradshaw,F,19.0,163.0,57.0,Great Britain,GBR,1976 Summer,1976,Summer,Montreal,Swimming,Swimming Women's 200 metres Freestyle,NaN
241090,120757,Shuichi Toki,M,24.0,175.0,65.0,Japan,JPN,1988 Summer,1988,Summer,Seoul,Equestrianism,"Equestrianism Mixed Jumping, Team",NaN
92306,46751,"Benjamin Robert ""Ben"" Hawes",M,24.0,175.0,73.0,Great Britain,GBR,2004 Summer,2004,Summer,Athina,Hockey,Hockey Men's Hockey,NaN
83037,42181,Zygmunt Marian Grabowski,M,43.0,NaN,NaN,Poland,POL,1936 Summer,1936,Summer,Berlin,Art Competitions,"Art Competitions Mixed Painting, Unknown Event",NaN

In [155]:
region_df.sample(5)

     NOC             region notes
120  LIE      Liechtenstein   NaN
72   GAB              Gabon   NaN
38   CGO  Republic of Congo   NaN
197  TCH     Czech Republic   NaN
10   ARU              Aruba   NaN

In [156]:
df = df.merge(region_df, on = 'NOC', how = 'left')

In [157]:
df.sample(4)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes
122365,74790,Umberto Marcheggiani,M,25.0,180.0,90.0,Italy,ITA,1968 Summer,1968,Summer,Mexico City,Wrestling,"Wrestling Men's Middleweight, Freestyle",NaN,Italy,NaN
177757,108610,Jean-Michel Sngal,M,31.0,185.0,NaN,France,FRA,1984 Summer,1984,Summer,Los Angeles,Basketball,Basketball Men's Basketball,NaN,France,NaN
217865,132720,Terap Adoum Yaya,M,17.0,185.0,70.0,Chad,CHA,1992 Summer,1992,Summer,Barcelona,Athletics,Athletics Men's 800 metres,NaN,Chad,NaN
116668,71361,"Mara Gabriela ""Gaby"" Lpez Butron",F,22.0,168.0,58.0,Mexico,MEX,2016 Summer,2016,Summer,Rio de Janeiro,Golf,Golf Women's Individual,NaN,Mexico,NaN

In [158]:
df['region'].unique().shape

(206,)

In [159]:
df.isnull().sum()

ID             0
Name           0
Sex            0
Age         9189
Height     51857
Weight     53854
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     188464
region       370
notes     218151
dtype: int64

In [160]:
df.duplicated().sum()

np.int64(1385)

In [161]:
df.drop_duplicates(inplace = True)

In [162]:
df['Medal'].value_counts()

Medal
Gold      11456
Bronze    11409
Silver    11212
Name: count, dtype: int64

In [163]:
df = pd.concat([df,pd.get_dummies(df['Medal'])], axis=1)

In [164]:
df.sample(4)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
78791,48097,Yurisandy Hernndez Ros,M,26.0,172.0,75.0,Cuba,CUB,2016 Summer,2016,Summer,Rio de Janeiro,Wrestling,"Wrestling Men's Middleweight, Greco-Roman",NaN,Cuba,NaN,False,False,False
162213,98928,Jean-Louis Rapnouil,M,26.0,174.0,69.0,France,FRA,1992 Summer,1992,Summer,Barcelona,Athletics,Athletics Men's 4 x 400 metres Relay,NaN,France,NaN,False,False,False
125360,76605,Hiroshi Matsunobu,M,20.0,NaN,NaN,Japan,JPN,1936 Summer,1936,Summer,Berlin,Gymnastics,Gymnastics Men's Individual All-Around,NaN,Japan,NaN,False,False,False
67417,41072,Santiago Goicoechea Orsolides,M,23.0,NaN,NaN,Spain,ESP,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,NaN,Spain,NaN,False,False,False

In [165]:
df.groupby('NOC')[['Bronze', 'Gold', 'Silver']].sum().sort_values('Gold', ascending=False).reset_index()

     NOC  Bronze  Gold  Silver
0    USA    1197  2472    1333
1    URS     596   832     635
2    GBR     620   635     729
3    GER     649   592     538
4    ITA     454   518     474
..   ...     ...   ...     ...
225  WIF       5     0       0
226  YEM       0     0       0
227  YAR       0     0       0
228  YMD       0     0       0
229  ZAM       1     0       1

[230 rows x 4 columns]

In [166]:
medel_tally['Total'] = medel_tally['Gold'] + medel_tally['Silver'] + medel_tally['Bronze']
medel_tally

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,...,Sport,Event,Medal,region,notes,Bronze,Gold,Silver,total,Total
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,...,Basketball,Basketball Men's Basketball,NaN,China,NaN,False,False,False,False,False
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,...,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN,False,False,False,False,False
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,...,Football,Football Men's Football,NaN,Denmark,NaN,False,False,False,False,False
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,...,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN,False,True,False,True,True
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,...,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222528,135553,Galina Ivanovna Zybina (-Fyodorova),F,25.0,168.0,80.0,Soviet Union,URS,1956 Summer,1956,...,Athletics,Athletics Women's Shot Put,Silver,Russia,NaN,False,False,True,True,True
222530,135553,Galina Ivanovna Zybina (-Fyodorova),F,33.0,168.0,80.0,Soviet Union,URS,1964 Summer,1964,...,Athletics,Athletics Women's Shot Put,Bronze,Russia,NaN,True,False,False,True,True
222536,135556,Bogusaw Stanisaw Zychowicz,M,19.0,189.0,80.0,Poland,POL,1980 Summer,1980,...,Swimming,Swimming Men's 100 metres Butterfly,NaN,Poland,NaN,False,False,False,False,False
222537,135556,Bogusaw Stanisaw Zychowicz,M,19.0,189.0,80.0,Poland,POL,1980 Summer,1980,...,Swimming,Swimming Men's 200 metres Butterfly,NaN,Poland,NaN,False,False,False,False,False
222541,135560,Stavroula Zygouri,F,36.0,171.0,63.0,Greece,GRE,2004 Summer,2004,...,Wrestling,"Wrestling Women's Middleweight, Freestyle",NaN,Greece,NaN,False,False,False,False,False

In [167]:
medel_tally = df.drop_duplicates(subset=['Team', 'NOC', 'Games', 'Year', 'City', 'Sport', 'Event', 'Medal'])

In [168]:
medel_tally = medel_tally.groupby('NOC').sum()[['Gold', 'Silver', 'Bronze']].sort_values('Gold',ascending=False).reset_index()

In [169]:
medel_tally['total'] = medel_tally['Gold'] + medel_tally['Silver'] + medel_tally['Bronze']

In [170]:
medel_tally.sample(4)

     NOC  Gold  Silver  Bronze  total
35   AUT    26      40      42    108
163  KIR     0       0       0      0
107  ISV     0       1       0      1
206  SMR     0       0       0      0

In [171]:
medel_tally[medel_tally['NOC'] == 'BAN']

     NOC  Gold  Silver  Bronze  total
136  BAN     0       0       0      0

In [172]:
years =  df['Year'].unique().tolist()

In [173]:
years.sort()
years.insert(0, 'Overall')

In [174]:
years

['Overall',
 1896,
 1900,
 1904,
 1906,
 1908,
 1912,
 1920,
 1924,
 1928,
 1932,
 1936,
 1948,
 1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008,
 2012,
 2016]

In [175]:
conutry =  df['region'].unique().tolist()

In [176]:
country = np.unique(df['region'].dropna().values.tolist()).tolist()

In [177]:
country.sort()

In [178]:
country

['Afghanistan',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Antigua',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Boliva',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Cook Islands',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Curacao',
 'Cyprus',
 'Czech Republic',
 'Democratic Republic of the Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Individual Olympic Athletes',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Republic of Congo',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts',
 'Saint Lucia',
 'Saint Vincent',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'UK',
 'USA',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'Virgin Islands, British',
 'Virgin Islands, US',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [179]:
country.insert(0, 'Country')

In [180]:
country

['Country',
 'Afghanistan',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Antigua',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Boliva',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Cook Islands',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Curacao',
 'Cyprus',
 'Czech Republic',
 'Democratic Republic of the Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Individual Olympic Athletes',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Republic of Congo',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts',
 'Saint Lucia',
 'Saint Vincent',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'UK',
 'USA',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'Virgin Islands, British',
 'Virgin Islands, US',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [192]:
def fatch_medal_tally(df,year, country):
  medel_df = df.drop_duplicates(subset=['Team', 'NOC', 'Games', 'Year', 'City', 'Sport', 'Event', 'Medal'])
  flag = 0
  if year == 'Overall' and country == 'Overall':
    temp_df = df
  if year == 'Overall' and country != 'Overall':
    flag = 1
    temp_df = medel_df[medel_df['region'] == country]
  if year != 'Overall' and country == 'Overall':
    temp_df = medel_df[medel_df['Year'] == year]
  if year != 'Overall' and country != 'Overall':
    temp_df = medel_df[(medel_df['Year'] == year) & (medel_df['region'] == country)]

  if flag == 1:
    x = temp_df.groupby('Year').sum()[['Gold', 'Silver', 'Bronze']].sort_values('Year',ascending=True).reset_index()
  else:
    x = temp_df.groupby('region').sum()[['Gold', 'Silver', 'Bronze']].sort_values('Gold',ascending=False).reset_index()
  x['total'] = x['Gold'] + x['Silver'] + x['Bronze']
  print(x)

In [195]:
fatch_medal_tally(year = 'Overall', country = 'India')

    Year  Gold  Silver  Bronze  total
0   1900     0       2       0      2
1   1920     0       0       0      0
2   1924     0       0       0      0
3   1928     1       0       0      1
4   1932     1       0       0      1
5   1936     1       0       0      1
6   1948     1       0       0      1
7   1952     1       0       1      2
8   1956     1       0       0      1
9   1960     0       1       0      1
10  1964     1       0       0      1
11  1968     0       0       1      1
12  1972     0       0       1      1
13  1976     0       0       0      0
14  1980     1       0       0      1
15  1984     0       0       0      0
16  1988     0       0       0      0
17  1992     0       0       0      0
18  1996     0       0       1      1
19  2000     0       0       1      1
20  2004     0       1       0      1
21  2008     1       0       2      3
22  2012     0       2       4      6
23  2016     0       1       1      2

In [183]:
medel_df = df.drop_duplicates(subset=['Team', 'NOC', 'Games', 'Year', 'City', 'Sport', 'Event', 'Medal'])

In [184]:
medel_df[(medel_df['Year'] == 2016) & (medel_df['region'] == 'India')]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
1015,663,Sharath Kamal Achanta,M,34.0,186.0,85.0,India,IND,2016 Summer,2016,Summer,Rio de Janeiro,Table Tennis,Table Tennis Men's Singles,NaN,India,NaN,False,False,False
7065,4523,Seema Antil,F,33.0,182.0,92.0,India,IND,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,Athletics Women's Discus Throw,NaN,India,NaN,False,False,False
8713,5562,Aditi Ashok,F,18.0,173.0,57.0,India,IND,2016 Summer,2016,Summer,Rio de Janeiro,Golf,Golf Women's Individual,NaN,India,NaN,False,False,False
9202,5868,Manu Attri,M,23.0,172.0,73.0,India,IND,2016 Summer,2016,Summer,Rio de Janeiro,Badminton,Badminton Men's Doubles,NaN,India,NaN,False,False,False
10070,6427,Lalita Shivaji Babar,F,27.0,166.0,50.0,India,IND,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,"Athletics Women's 3,000 metres Steeplechase",NaN,India,NaN,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182260,111467,Sathish Kumar Sivalingam,M,24.0,175.0,77.0,India,IND,2016 Summer,2016,Summer,Rio de Janeiro,Weightlifting,Weightlifting Men's Middleweight,NaN,India,NaN,False,False,False
195568,119515,Shiva Thapa,M,22.0,169.0,56.0,India,IND,2016 Summer,2016,Summer,Rio de Janeiro,Boxing,Boxing Men's Bantamweight,NaN,India,NaN,False,False,False
198042,120871,Sandeep Tomar,M,25.0,168.0,61.0,India,IND,2016 Summer,2016,Summer,Rio de Janeiro,Wrestling,"Wrestling Men's Featherweight, Freestyle",NaN,India,NaN,False,False,False
216942,132143,Vikas Krishan Yadav,M,24.0,177.0,69.0,India,IND,2016 Summer,2016,Summer,Rio de Janeiro,Boxing,Boxing Men's Middleweight,NaN,India,NaN,False,False,False
216985,132177,Mohammad Anas Yahiya,M,21.0,177.0,69.0,India,IND,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,Athletics Men's 400 metres,NaN,India,NaN,False,False,False