<a href="https://colab.research.google.com/github/Ebratul/Python/blob/main/House%20Price/traindata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [313]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import numpy as np
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from scipy import stats
# import warnings
# warnings.filterwarnings('ignore')
# %matplotlib inline

In [314]:
df = pd.read_csv(r"/content/drive/MyDrive/dataset/train.csv")
pd.set_option('display.max_columns', None)

In [315]:
df.sample(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1169,1170,60,RL,118.0,35760,Pave,NaN,IR1,Lvl,AllPub,CulDSac,Gtl,NoRidge,Norm,Norm,1Fam,2Story,10,5,1995,1996,Hip,CompShg,HdBoard,HdBoard,BrkFace,1378.0,Gd,Gd,PConc,Ex,TA,Gd,GLQ,1387,Unf,0,543,1930,GasA,Ex,Y,SBrkr,1831,1796,0,3627,1,0,3,1,4,1,Gd,10,Typ,1,TA,Attchd,1995.0,Fin,3,807,TA,TA,Y,361,76,0,0,0,0,NaN,NaN,NaN,0,7,2006,WD,Normal,625000
482,483,70,RM,50.0,2500,Pave,Pave,Reg,Lvl,AllPub,Corner,Gtl,OldTown,Norm,Norm,1Fam,2Story,7,8,1915,2005,Gable,CompShg,Stucco,Stucco,NaN,0.0,Gd,TA,PConc,TA,TA,No,ALQ,299,Unf,0,611,910,GasA,Ex,Y,SBrkr,916,910,0,1826,1,0,1,1,4,1,Ex,7,Min2,1,Gd,Attchd,1915.0,Unf,1,164,Fa,Fa,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,6,2009,WD,Normal,155000
1331,1332,80,RL,55.0,10780,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,SLvl,5,5,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,TA,TA,Av,ALQ,483,Unf,0,428,911,GasA,Gd,Y,SBrkr,954,0,0,954,0,0,1,0,3,1,TA,6,Typ,0,NaN,Detchd,1976.0,Unf,2,576,TA,TA,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,7,2006,WD,Normal,132500
170,171,50,RM,NaN,12358,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,OldTown,Feedr,Norm,1Fam,1.5Fin,5,6,1941,1950,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,TA,TA,No,Rec,360,Unf,0,360,720,GasA,TA,Y,SBrkr,854,0,528,1382,0,0,1,1,2,1,TA,7,Typ,0,NaN,Detchd,1991.0,Unf,2,660,TA,TA,Y,237,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,128500
1233,1234,20,RL,NaN,12160,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,5,1959,1959,Hip,CompShg,Plywood,Plywood,BrkFace,180.0,TA,TA,CBlock,TA,TA,No,Rec,1000,Unf,0,188,1188,GasA,Fa,Y,SBrkr,1188,0,0,1188,1,0,1,0,3,1,TA,6,Typ,0,NaN,Attchd,1959.0,RFn,2,531,TA,TA,Y,0,0,0,0,0,0,NaN,MnPrv,NaN,0,5,2010,COD,Abnorml,142000

In [316]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [317]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [318]:
df.shape

(1460, 81)

In [319]:
sb.heatmap(df.isnull(), yticklabels = False, cbar = False, cmap = 'viridis')

In [320]:
pd.set_option('display.max_rows', None)
df.isnull().sum()

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType        872
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinSF1          0
BsmtFinType2       38
BsmtFinSF2          0
BsmtUnfSF           0
TotalBsmtSF         0
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        0
BsmtHalfBath        0
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         0
TotRmsAbvGrd        0
Functional          0
Fireplaces          0
FireplaceQu       690
GarageType         81
GarageYrBlt        81
GarageFinish       81
GarageCars          0
GarageArea          0
GarageQual         81
GarageCond         81
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1453
Fence            1179
MiscFeature      1406
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice           0
dtype: int64

In [321]:
df = df.drop(columns=['MiscFeature','Fence', 'PoolQC', 'FireplaceQu','MasVnrType' ,'Alley'])

In [322]:
df.shape

(1460, 75)

In [323]:
plt.figure(figsize=(12,6))
sb.heatmap(df.isnull(), yticklabels=False, cbar=False)

In [324]:
df.sample(7)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1340,1341,20,RL,70.0,8294,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,4,5,1971,1971,Gable,CompShg,MetalSd,MetalSd,0.0,TA,TA,CBlock,TA,TA,No,Unf,0,Unf,0,858,858,GasA,TA,Y,SBrkr,872,0,0,872,0,0,1,0,3,1,TA,5,Typ,0,Detchd,1974.0,Unf,4,480,TA,TA,Y,0,0,0,0,0,0,0,6,2007,WD,Normal,123000
123,124,120,RL,55.0,7892,Pave,Reg,Lvl,AllPub,Inside,Gtl,SawyerW,Norm,Norm,TwnhsE,1Story,6,5,1993,1993,Gable,CompShg,Plywood,Plywood,0.0,Gd,TA,PConc,Gd,TA,No,GLQ,300,Unf,0,899,1199,GasA,Ex,Y,SBrkr,1199,0,0,1199,0,0,2,0,2,1,Gd,5,Typ,0,Attchd,1993.0,RFn,2,530,TA,TA,Y,0,63,0,0,0,0,0,3,2008,WD,Normal,153900
365,366,70,RM,59.0,10690,Pave,Reg,Lvl,AllPub,Inside,Gtl,IDOTRR,Norm,Norm,1Fam,2Story,5,7,1920,1997,Hip,CompShg,VinylSd,VinylSd,0.0,TA,Gd,CBlock,TA,Fa,No,Rec,456,Unf,0,216,672,GasA,Gd,Y,FuseA,672,672,0,1344,0,0,1,0,3,1,TA,6,Typ,0,Detchd,1964.0,Unf,1,468,TA,Fa,Y,0,128,218,0,0,0,0,7,2009,WD,Normal,147000
306,307,60,RL,116.0,13474,Pave,Reg,Lvl,AllPub,Inside,Gtl,SawyerW,Feedr,Norm,1Fam,2Story,7,5,1990,1991,Gable,CompShg,HdBoard,Plywood,246.0,Gd,TA,CBlock,Gd,TA,No,ALQ,700,Unf,0,0,700,GasA,Gd,Y,SBrkr,1122,1121,0,2243,1,0,2,1,4,1,Gd,8,Typ,1,Attchd,1990.0,RFn,3,746,TA,TA,Y,127,44,224,0,0,0,0,6,2007,WD,Normal,225000
1268,1269,50,RL,NaN,14100,Pave,IR1,Lvl,AllPub,Inside,Mod,Crawfor,Norm,Norm,1Fam,1.5Fin,8,9,1935,1997,Gable,CompShg,Stucco,Stucco,632.0,TA,Gd,CBlock,TA,TA,Mn,Rec,192,Unf,0,536,728,GasA,Ex,Y,SBrkr,1968,1479,0,3447,0,0,3,1,4,1,Gd,11,Typ,2,BuiltIn,1982.0,Unf,3,1014,TA,TA,Y,314,12,0,0,0,0,0,5,2008,WD,Normal,381000
1387,1388,50,RM,60.0,8520,Pave,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Artery,Norm,1Fam,1.5Fin,6,7,1916,1950,Gable,CompShg,Stucco,Stucco,0.0,TA,Gd,BrkTil,TA,TA,No,Rec,168,LwQ,546,0,714,GasW,TA,N,SBrkr,1664,862,0,2526,0,0,2,0,5,1,Gd,10,Typ,1,Detchd,1916.0,Unf,1,216,TA,TA,Y,88,15,0,0,0,0,0,8,2007,CWD,Family,136000
302,303,20,RL,118.0,13704,Pave,IR1,Lvl,AllPub,Corner,Gtl,CollgCr,Norm,Norm,1Fam,1Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,150.0,Gd,TA,PConc,Gd,TA,No,Unf,0,Unf,0,1541,1541,GasA,Ex,Y,SBrkr,1541,0,0,1541,0,0,2,0,3,1,Gd,6,Typ,1,Attchd,2001.0,RFn,3,843,TA,TA,Y,468,81,0,0,0,0,0,1,2006,WD,Normal,205000

In [325]:
#Fill missing values
df['LotFrontage'] = df['LotFrontage'].fillna(df['LotFrontage'].mean())

In [326]:
df['BsmtQual'].value_counts()

BsmtQual
TA    649
Gd    618
Ex    121
Fa     35
Name: count, dtype: int64

In [327]:
df['BsmtCond'].value_counts()

BsmtCond
TA    1311
Gd      65
Fa      45
Po       2
Name: count, dtype: int64

In [328]:
df['BsmtQual'] = df['BsmtQual'].fillna(df['BsmtQual'].mode()[0])
df['BsmtCond'] = df['BsmtCond'].fillna(df['BsmtCond'].mode()[0])

In [329]:
df['BsmtExposure'].value_counts()

BsmtExposure
No    953
Av    221
Gd    134
Mn    114
Name: count, dtype: int64

In [330]:
df['BsmtFinType1'].value_counts()

BsmtFinType1
Unf    430
GLQ    418
ALQ    220
BLQ    148
Rec    133
LwQ     74
Name: count, dtype: int64

In [331]:
df['BsmtFinType2'].value_counts()

BsmtFinType2
Unf    1256
Rec      54
LwQ      46
BLQ      33
ALQ      19
GLQ      14
Name: count, dtype: int64

In [332]:
df['BsmtExposure'] = df['BsmtExposure'].fillna(df['BsmtExposure'].mode()[0])
df['BsmtFinType1'] = df['BsmtFinType1'].fillna(df['BsmtFinType1'].mode()[0])
df['BsmtFinType2'] = df['BsmtFinType2'].fillna(df['BsmtFinType2'].mode()[0])

In [333]:
df['GarageType'].value_counts()

GarageType
Attchd     870
Detchd     387
BuiltIn     88
Basment     19
CarPort      9
2Types       6
Name: count, dtype: int64

In [334]:
df['GarageYrBlt'].value_counts()

GarageYrBlt
2005.0    65
2006.0    59
2004.0    53
2003.0    50
2007.0    49
1977.0    35
1998.0    31
1999.0    30
1976.0    29
2008.0    29
2000.0    27
1968.0    26
2002.0    26
1950.0    24
1993.0    22
1965.0    21
1966.0    21
1958.0    21
2009.0    21
1962.0    21
1970.0    20
1996.0    20
2001.0    20
1957.0    20
1954.0    19
1960.0    19
1978.0    19
1997.0    19
1974.0    18
1964.0    18
1995.0    18
1994.0    18
1959.0    17
1990.0    16
1963.0    16
1956.0    16
1967.0    15
1980.0    15
1979.0    15
1969.0    15
1920.0    14
1940.0    14
1972.0    14
1973.0    14
1988.0    14
1971.0    13
1961.0    13
1955.0    13
1992.0    13
1953.0    12
1987.0    11
1948.0    11
1925.0    10
1941.0    10
1985.0    10
1981.0    10
1989.0    10
1939.0     9
1975.0     9
1991.0     9
1930.0     8
1949.0     8
1984.0     8
1983.0     7
1926.0     6
1951.0     6
1986.0     6
1936.0     5
1916.0     5
1922.0     5
1931.0     4
1945.0     4
1935.0     4
1928.0     4
1946.0     4
1982.0     4
1923.0     3
1938.0     3
1910.0     3
1921.0     3
1932.0     3
1952.0     3
2010.0     3
1924.0     3
1915.0     2
1929.0     2
1918.0     2
1947.0     2
1937.0     2
1914.0     2
1942.0     2
1934.0     2
1900.0     1
1927.0     1
1906.0     1
1908.0     1
1933.0     1
Name: count, dtype: int64

In [335]:
df['GarageFinish'].value_counts()

GarageFinish
Unf    605
RFn    422
Fin    352
Name: count, dtype: int64

In [336]:
df['GarageQual'].value_counts()

GarageQual
TA    1311
Fa      48
Gd      14
Ex       3
Po       3
Name: count, dtype: int64

In [337]:
df['GarageCond'].value_counts()

GarageCond
TA    1326
Fa      35
Gd       9
Po       7
Ex       2
Name: count, dtype: int64

In [338]:
df['GarageType'] = df['GarageType'].fillna(df['GarageType'].mode()[0])
df['GarageYrBlt'] = df['GarageYrBlt'].fillna(df['GarageYrBlt'].mode()[0])
df['GarageFinish'] = df['GarageFinish'].fillna(df['GarageFinish'].mode()[0])
df['GarageQual'] = df['GarageQual'].fillna(df['GarageQual'].mode()[0])
df['GarageCond'] = df['GarageCond'].fillna(df['GarageCond'].mode()[0])

In [339]:
# df.drop(['Id'], axis = 1, inplace = True)

In [340]:
df.shape

(1460, 75)

In [341]:
plt.figure(figsize=(12,6))
sb.heatmap(df.isnull(), yticklabels=False, cbar=False)

In [342]:
df.dropna(inplace=True)

In [343]:
df.shape

(1451, 75)

In [344]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrArea', 'ExterQual',
       'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
       'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF',
       'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical',
       '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath',
       'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr',
       'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice'],
      dtype='object')

In [345]:
df.head(3)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,0,9,2008,WD,Normal,223500

In [346]:
columns = [
    'MSZoning',
    'Street',
    'LotShape',
    'LandContour',
    'Utilities',
    'LotConfig',
    'LandSlope',
    'Neighborhood',
    'Condition1',
    'Condition2',
    'BldgType',
    'HouseStyle',
    'RoofStyle',
    'RoofMatl',
    'Exterior1st',
    'Exterior2nd',
    'ExterQual',
    'ExterCond',
    'Foundation',
    'BsmtQual',
    'BsmtCond',
    'BsmtExposure',
    'BsmtFinType1',
    'BsmtFinType2',
    'Heating',
    'HeatingQC',
    'CentralAir',
    'Electrical',
    'KitchenQual',
    'Functional',
    'GarageType',
    'GarageFinish',
    'GarageQual',
    'GarageCond',
    'PavedDrive',
    'SaleType',
    'SaleCondition'
]

In [347]:
# y_df_test = df[['SalePrice']]
# y_df_test=y_df_test.iloc[:1422,:]

In [348]:
# y_df_test=y_df_test.iloc[:1422,:]

In [349]:
# y_df_test.shape

In [350]:
def category_onehot_multcols(multcolumns):
    df_final=final_df
    i=0
    for fields in multcolumns:

        print(fields)
        df1=pd.get_dummies(final_df[fields],drop_first=True)

        final_df.drop([fields],axis=1,inplace=True)
        if i==0:
            df_final=df1.copy()
        else:

            df_final=pd.concat([df_final,df1],axis=1)
        i=i+1


    df_final=pd.concat([final_df,df_final],axis=1)

    return df_final

In [351]:
main_df = df.copy()

In [352]:
# df.drop(['Id'], axis = 1, inplace = True)

In [353]:
test_df = pd.read_csv(r"/content/drive/MyDrive/dataset/formulatedTest.csv")
test_df.head(3)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,0.0,TA,TA,CBlock,TA,TA,No,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896,0,0,896,0.0,0.0,1,0,2,1,TA,5,Typ,0,Attchd,1961.0,Unf,1.0,730.0,TA,TA,Y,140,0,0,0,120,0,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,108.0,TA,TA,CBlock,TA,TA,No,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329,0,0,1329,0.0,0.0,1,1,3,1,Gd,6,Typ,0,Attchd,1958.0,Unf,1.0,312.0,TA,TA,Y,393,36,0,0,0,0,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,5,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,0.0,TA,TA,PConc,Gd,TA,No,GLQ,791.0,Unf,0.0,137.0,928.0,GasA,Gd,Y,SBrkr,928,701,0,1629,0.0,0.0,2,1,3,1,TA,6,Typ,1,Attchd,1997.0,Fin,2.0,482.0,TA,TA,Y,212,34,0,0,0,0,0,3,2010,WD,Normal

In [354]:
test_df.shape

(1449, 74)

In [355]:
test_df.drop(['Id'], axis = 1, inplace = True)

In [356]:
final_df = pd.concat([df, test_df], axis= 0)

In [357]:
final_df.shape

(2900, 75)

In [358]:
final_df.head(4)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1.0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706.0,Unf,0.0,150.0,856.0,GasA,Ex,Y,SBrkr,856,854,0,1710,1.0,0.0,2,1,3,1,Gd,8,Typ,0,Attchd,2003.0,RFn,2.0,548.0,TA,TA,Y,0,61,0,0,0,0,0,2,2008,WD,Normal,208500.0
1,2.0,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978.0,Unf,0.0,284.0,1262.0,GasA,Ex,Y,SBrkr,1262,0,0,1262,0.0,1.0,2,0,3,1,TA,6,Typ,1,Attchd,1976.0,RFn,2.0,460.0,TA,TA,Y,298,0,0,0,0,0,0,5,2007,WD,Normal,181500.0
2,3.0,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486.0,Unf,0.0,434.0,920.0,GasA,Ex,Y,SBrkr,920,866,0,1786,1.0,0.0,2,1,3,1,Gd,6,Typ,1,Attchd,2001.0,RFn,2.0,608.0,TA,TA,Y,0,42,0,0,0,0,0,9,2008,WD,Normal,223500.0
3,4.0,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216.0,Unf,0.0,540.0,756.0,GasA,Gd,Y,SBrkr,961,756,0,1717,1.0,0.0,1,0,3,1,Gd,7,Typ,1,Detchd,1998.0,Unf,3.0,642.0,TA,TA,Y,0,35,272,0,0,0,0,2,2006,WD,Abnorml,140000.0

In [359]:
final_df = category_onehot_multcols(columns)

MSZoning
Street
LotShape
LandContour
Utilities
LotConfig
LandSlope
Neighborhood
Condition1
Condition2
BldgType
HouseStyle
RoofStyle
RoofMatl
Exterior1st
Exterior2nd
ExterQual
ExterCond
Foundation
BsmtQual
BsmtCond
BsmtExposure
BsmtFinType1
BsmtFinType2
Heating
HeatingQC
CentralAir
Electrical
KitchenQual
Functional
GarageType
GarageFinish
GarageQual
GarageCond
PavedDrive
SaleType
SaleCondition

In [360]:
final_df.head(5)

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice,FV,RH,RL,RM,Pave,IR2,IR3,Reg,HLS,Low,Lvl,NoSeWa,CulDSac,FR2,FR3,Inside,Mod,Sev,Blueste,BrDale,BrkSide,ClearCr,CollgCr,Crawfor,Edwards,Gilbert,IDOTRR,MeadowV,Mitchel,NAmes,NPkVill,NWAmes,NoRidge,NridgHt,OldTown,SWISU,Sawyer,SawyerW,Somerst,StoneBr,Timber,Veenker,Feedr,Norm,PosA,PosN,RRAe,RRAn,RRNe,RRNn,Feedr,Norm,PosA,PosN,RRAe,RRAn,RRNn,2fmCon,Duplex,Twnhs,TwnhsE,1.5Unf,1Story,2.5Fin,2.5Unf,2Story,SFoyer,SLvl,Gable,Gambrel,Hip,Mansard,Shed,CompShg,Membran,Metal,Roll,Tar&Grv,WdShake,WdShngl,AsphShn,BrkComm,BrkFace,CBlock,CemntBd,HdBoard,ImStucc,MetalSd,Plywood,Stone,Stucco,VinylSd,Wd Sdng,WdShing,AsphShn,Brk Cmn,BrkFace,CBlock,CmentBd,HdBoard,ImStucc,MetalSd,Other,Plywood,Stone,Stucco,VinylSd,Wd Sdng,Wd Shng,Fa,Gd,TA,Fa,Gd,Po,TA,CBlock,PConc,Slab,Stone,Wood,Fa,Gd,TA,Gd,Po,TA,Gd,Mn,No,BLQ,GLQ,LwQ,Rec,Unf,BLQ,GLQ,LwQ,Rec,Unf,GasA,GasW,Grav,OthW,Wall,Fa,Gd,Po,TA,Y,FuseF,FuseP,Mix,SBrkr,Fa,Gd,TA,Maj2,Min1,Min2,Mod,Sev,Typ,Attchd,Basment,BuiltIn,CarPort,Detchd,RFn,Unf,Fa,Gd,Po,TA,Fa,Gd,Po,TA,P,Y,CWD,Con,ConLD,ConLI,ConLw,New,Oth,WD,AdjLand,Alloca,Family,Normal,Partial
0,1.0,60,65.0,8450,7,5,2003,2003,196.0,706.0,0.0,150.0,856.0,856,854,0,1710,1.0,0.0,2,1,3,1,8,0,2003.0,2.0,548.0,0,61,0,0,0,0,0,2,2008,208500.0,False,False,True,False,True,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,True,False,False,False,True,False,False,True,False,True,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,True,True,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False
1,2.0,20,80.0,9600,6,8,1976,1976,0.0,978.0,0.0,284.0,1262.0,1262,0,0,1262,0.0,1.0,2,0,3,1,6,1,1976.0,2.0,460.0,298,0,0,0,0,0,0,5,2007,181500.0,False,False,True,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,False,False,False,True,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,True,False,False,False,False,False,True,True,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False
2,3.0,60,68.0,11250,7,5,2001,2002,162.0,486.0,0.0,434.0,920.0,920,866,0,1786,1.0,0.0,2,1,3,1,6,1,2001.0,2.0,608.0,0,42,0,0,0,0,0,9,2008,223500.0,False,False,True,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,True,False,False,False,True,False,True,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,True,True,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False
3,4.0,70,60.0,9550,7,5,1915,1970,0.0,216.0,0.0,540.0,756.0,961,756,0,1717,1.0,0.0,1,0,3,1,7,1,1998.0,3.0,642.0,0,35,272,0,0,0,0,2,2006,140000.0,False,False,True,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,True,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False
4,5.0,60,84.0,14260,8,5,2000,2000,350.0,655.0,0.0,490.0,1145.0,1145,1053,0,2198,1.0,0.0,2,1,4,1,9,1,2000.0,3.0,836.0,192,84,0,0,0,0,0,12,2008,250000.0,False,False,True,False,True,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,True,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,True,True,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False

In [361]:
final_df.columns[final_df.columns.duplicated()]

Index(['Feedr', 'Norm', 'PosA', 'PosN', 'RRAe', 'RRAn', 'RRNn', 'AsphShn',
       'BrkFace', 'CBlock', 'HdBoard', 'ImStucc', 'MetalSd', 'Plywood',
       'Stone', 'Stucco', 'VinylSd', 'Wd Sdng', 'Fa', 'Gd', 'TA', 'CBlock',
       'Stone', 'Fa', 'Gd', 'TA', 'Gd', 'Po', 'TA', 'Gd', 'BLQ', 'GLQ', 'LwQ',
       'Rec', 'Unf', 'Fa', 'Gd', 'Po', 'TA', 'Fa', 'Gd', 'TA', 'Mod', 'Sev',
       'Unf', 'Fa', 'Gd', 'Po', 'TA', 'Fa', 'Gd', 'Po', 'TA', 'Y'],
      dtype='object')

In [362]:
#যদি শুধু unique columns রাখতে চাও:
final_df = final_df.loc[:,~final_df.columns.duplicated()]

In [363]:
final_df.head(3)

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice,FV,RH,RL,RM,Pave,IR2,IR3,Reg,HLS,Low,Lvl,NoSeWa,CulDSac,FR2,FR3,Inside,Mod,Sev,Blueste,BrDale,BrkSide,ClearCr,CollgCr,Crawfor,Edwards,Gilbert,IDOTRR,MeadowV,Mitchel,NAmes,NPkVill,NWAmes,NoRidge,NridgHt,OldTown,SWISU,Sawyer,SawyerW,Somerst,StoneBr,Timber,Veenker,Feedr,Norm,PosA,PosN,RRAe,RRAn,RRNe,RRNn,2fmCon,Duplex,Twnhs,TwnhsE,1.5Unf,1Story,2.5Fin,2.5Unf,2Story,SFoyer,SLvl,Gable,Gambrel,Hip,Mansard,Shed,CompShg,Membran,Metal,Roll,Tar&Grv,WdShake,WdShngl,AsphShn,BrkComm,BrkFace,CBlock,CemntBd,HdBoard,ImStucc,MetalSd,Plywood,Stone,Stucco,VinylSd,Wd Sdng,WdShing,Brk Cmn,CmentBd,Other,Wd Shng,Fa,Gd,TA,Po,PConc,Slab,Wood,Mn,No,BLQ,GLQ,LwQ,Rec,Unf,GasA,GasW,Grav,OthW,Wall,Y,FuseF,FuseP,Mix,SBrkr,Maj2,Min1,Min2,Typ,Attchd,Basment,BuiltIn,CarPort,Detchd,RFn,P,CWD,Con,ConLD,ConLI,ConLw,New,Oth,WD,AdjLand,Alloca,Family,Normal,Partial
0,1.0,60,65.0,8450,7,5,2003,2003,196.0,706.0,0.0,150.0,856.0,856,854,0,1710,1.0,0.0,2,1,3,1,8,0,2003.0,2.0,548.0,0,61,0,0,0,0,0,2,2008,208500.0,False,False,True,False,True,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,True,False,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False
1,2.0,20,80.0,9600,6,8,1976,1976,0.0,978.0,0.0,284.0,1262.0,1262,0,0,1262,0.0,1.0,2,0,3,1,6,1,1976.0,2.0,460.0,298,0,0,0,0,0,0,5,2007,181500.0,False,False,True,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False
2,3.0,60,68.0,11250,7,5,2001,2002,162.0,486.0,0.0,434.0,920.0,920,866,0,1786,1.0,0.0,2,1,3,1,6,1,2001.0,2.0,608.0,0,42,0,0,0,0,0,9,2008,223500.0,False,False,True,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False

In [364]:
# final_df.drop(columns=['Id'],inplace=True)

In [365]:
final_df.shape

(2900, 177)

In [366]:
df_train = final_df.iloc[:1422,:]
df_test = final_df.iloc[1422:,:]

In [367]:
df_train.head(3)

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice,FV,RH,RL,RM,Pave,IR2,IR3,Reg,HLS,Low,Lvl,NoSeWa,CulDSac,FR2,FR3,Inside,Mod,Sev,Blueste,BrDale,BrkSide,ClearCr,CollgCr,Crawfor,Edwards,Gilbert,IDOTRR,MeadowV,Mitchel,NAmes,NPkVill,NWAmes,NoRidge,NridgHt,OldTown,SWISU,Sawyer,SawyerW,Somerst,StoneBr,Timber,Veenker,Feedr,Norm,PosA,PosN,RRAe,RRAn,RRNe,RRNn,2fmCon,Duplex,Twnhs,TwnhsE,1.5Unf,1Story,2.5Fin,2.5Unf,2Story,SFoyer,SLvl,Gable,Gambrel,Hip,Mansard,Shed,CompShg,Membran,Metal,Roll,Tar&Grv,WdShake,WdShngl,AsphShn,BrkComm,BrkFace,CBlock,CemntBd,HdBoard,ImStucc,MetalSd,Plywood,Stone,Stucco,VinylSd,Wd Sdng,WdShing,Brk Cmn,CmentBd,Other,Wd Shng,Fa,Gd,TA,Po,PConc,Slab,Wood,Mn,No,BLQ,GLQ,LwQ,Rec,Unf,GasA,GasW,Grav,OthW,Wall,Y,FuseF,FuseP,Mix,SBrkr,Maj2,Min1,Min2,Typ,Attchd,Basment,BuiltIn,CarPort,Detchd,RFn,P,CWD,Con,ConLD,ConLI,ConLw,New,Oth,WD,AdjLand,Alloca,Family,Normal,Partial
0,1.0,60,65.0,8450,7,5,2003,2003,196.0,706.0,0.0,150.0,856.0,856,854,0,1710,1.0,0.0,2,1,3,1,8,0,2003.0,2.0,548.0,0,61,0,0,0,0,0,2,2008,208500.0,False,False,True,False,True,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,True,False,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False
1,2.0,20,80.0,9600,6,8,1976,1976,0.0,978.0,0.0,284.0,1262.0,1262,0,0,1262,0.0,1.0,2,0,3,1,6,1,1976.0,2.0,460.0,298,0,0,0,0,0,0,5,2007,181500.0,False,False,True,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False
2,3.0,60,68.0,11250,7,5,2001,2002,162.0,486.0,0.0,434.0,920.0,920,866,0,1786,1.0,0.0,2,1,3,1,6,1,2001.0,2.0,608.0,0,42,0,0,0,0,0,9,2008,223500.0,False,False,True,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False

In [368]:
df_test.head(3)

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice,FV,RH,RL,RM,Pave,IR2,IR3,Reg,HLS,Low,Lvl,NoSeWa,CulDSac,FR2,FR3,Inside,Mod,Sev,Blueste,BrDale,BrkSide,ClearCr,CollgCr,Crawfor,Edwards,Gilbert,IDOTRR,MeadowV,Mitchel,NAmes,NPkVill,NWAmes,NoRidge,NridgHt,OldTown,SWISU,Sawyer,SawyerW,Somerst,StoneBr,Timber,Veenker,Feedr,Norm,PosA,PosN,RRAe,RRAn,RRNe,RRNn,2fmCon,Duplex,Twnhs,TwnhsE,1.5Unf,1Story,2.5Fin,2.5Unf,2Story,SFoyer,SLvl,Gable,Gambrel,Hip,Mansard,Shed,CompShg,Membran,Metal,Roll,Tar&Grv,WdShake,WdShngl,AsphShn,BrkComm,BrkFace,CBlock,CemntBd,HdBoard,ImStucc,MetalSd,Plywood,Stone,Stucco,VinylSd,Wd Sdng,WdShing,Brk Cmn,CmentBd,Other,Wd Shng,Fa,Gd,TA,Po,PConc,Slab,Wood,Mn,No,BLQ,GLQ,LwQ,Rec,Unf,GasA,GasW,Grav,OthW,Wall,Y,FuseF,FuseP,Mix,SBrkr,Maj2,Min1,Min2,Typ,Attchd,Basment,BuiltIn,CarPort,Detchd,RFn,P,CWD,Con,ConLD,ConLI,ConLw,New,Oth,WD,AdjLand,Alloca,Family,Normal,Partial
1431,1432.0,120,70.049958,4928,6,6,1976,1976,0.0,958.0,0.0,0.0,958.0,958,0,0,958,0.0,0.0,2,0,2,1,5,0,1976.0,2.0,440.0,0,60,0,0,0,0,0,10,2009,143750.0,False,False,True,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,True,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False
1432,1433.0,30,60.000000,10800,4,6,1927,2007,0.0,0.0,0.0,656.0,656.0,968,0,0,968,0.0,0.0,2,0,4,1,5,0,1928.0,1.0,216.0,0,0,0,0,0,0,0,8,2007,64500.0,False,False,True,False,True,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,True,False,False,False,False,True,False,False,False,True,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False
1433,1434.0,60,93.000000,10261,6,5,2000,2000,318.0,0.0,0.0,936.0,936.0,962,830,0,1792,1.0,0.0,2,1,3,1,8,1,2000.0,2.0,451.0,0,0,0,0,0,0,0,5,2008,186500.0,False,False,True,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,False,False,False,True,True,False,False,False,False,True,False,False,False,True,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False

In [369]:
df_test.shape

(1478, 177)

In [370]:
df_test.drop(['SalePrice'], axis=1,inplace=True)

In [371]:
df_train['SalePrice'].head(3)

0    208500.0
1    181500.0
2    223500.0
Name: SalePrice, dtype: float64

In [372]:
df_test = df_test.iloc[:1422,:]
df_test.columns.difference(df_train.columns)

Index([], dtype='object')

In [373]:
df_test.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,FV,RH,RL,RM,Pave,IR2,IR3,Reg,HLS,Low,Lvl,NoSeWa,CulDSac,FR2,FR3,Inside,Mod,Sev,Blueste,BrDale,BrkSide,ClearCr,CollgCr,Crawfor,Edwards,Gilbert,IDOTRR,MeadowV,Mitchel,NAmes,NPkVill,NWAmes,NoRidge,NridgHt,OldTown,SWISU,Sawyer,SawyerW,Somerst,StoneBr,Timber,Veenker,Feedr,Norm,PosA,PosN,RRAe,RRAn,RRNe,RRNn,2fmCon,Duplex,Twnhs,TwnhsE,1.5Unf,1Story,2.5Fin,2.5Unf,2Story,SFoyer,SLvl,Gable,Gambrel,Hip,Mansard,Shed,CompShg,Membran,Metal,Roll,Tar&Grv,WdShake,WdShngl,AsphShn,BrkComm,BrkFace,CBlock,CemntBd,HdBoard,ImStucc,MetalSd,Plywood,Stone,Stucco,VinylSd,Wd Sdng,WdShing,Brk Cmn,CmentBd,Other,Wd Shng,Fa,Gd,TA,Po,PConc,Slab,Wood,Mn,No,BLQ,GLQ,LwQ,Rec,Unf,GasA,GasW,Grav,OthW,Wall,Y,FuseF,FuseP,Mix,SBrkr,Maj2,Min1,Min2,Typ,Attchd,Basment,BuiltIn,CarPort,Detchd,RFn,P,CWD,Con,ConLD,ConLI,ConLw,New,Oth,WD,AdjLand,Alloca,Family,Normal,Partial
1431,1432.0,120,70.049958,4928,6,6,1976,1976,0.0,958.0,0.0,0.0,958.0,958,0,0,958,0.0,0.0,2,0,2,1,5,0,1976.0,2.0,440.0,0,60,0,0,0,0,0,10,2009,False,False,True,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,True,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False
1432,1433.0,30,60.000000,10800,4,6,1927,2007,0.0,0.0,0.0,656.0,656.0,968,0,0,968,0.0,0.0,2,0,4,1,5,0,1928.0,1.0,216.0,0,0,0,0,0,0,0,8,2007,False,False,True,False,True,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,True,False,False,False,False,True,False,False,False,True,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False
1433,1434.0,60,93.000000,10261,6,5,2000,2000,318.0,0.0,0.0,936.0,936.0,962,830,0,1792,1.0,0.0,2,1,3,1,8,1,2000.0,2.0,451.0,0,0,0,0,0,0,0,5,2008,False,False,True,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,False,False,False,True,True,False,False,False,False,True,False,False,False,True,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False
1434,1435.0,20,80.000000,17400,5,5,1977,1977,0.0,936.0,0.0,190.0,1126.0,1126,0,0,1126,1.0,0.0,2,0,3,1,5,1,1977.0,2.0,484.0,295,41,0,0,0,0,0,5,2006,False,False,True,False,True,False,False,True,False,True,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,False,False,False,True,False,False,False,True,False
1435,1436.0,20,80.000000,8400,6,9,1962,2005,237.0,0.0,0.0,1319.0,1319.0,1537,0,0,1537,1.0,0.0,1,1,3,1,7,1,1962.0,2.0,462.0,0,36,0,0,0,0,0,7,2008,False,False,True,False,True,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,True,False,False,False,False,True,False,False,False,True,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [374]:
x_train = df_train.drop(['SalePrice'], axis = 1)
y_train = df_train['SalePrice']

In [375]:
x_train.shape

(1422, 176)

In [376]:
import xgboost
xgb=xgboost.XGBRegressor()
xgb.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [377]:
y_pred = xgb.predict(df_test)
len(y_pred)

1422

In [378]:
y_train = y_train.to_numpy()

In [379]:
from sklearn.metrics import mean_absolute_error
score = mean_absolute_error(y_train, y_pred)
score

79600.61828355749

In [380]:
xgb.score(x_train, y_train)

0.9995762710107099

In [381]:
# #Hyper parameter Optimization

# n_estimators = [100, 500, 900, 1100, 1500]

# max_depth = [2, 3, 5, 10, 15]
# booster = ['gbtree','gblinear']
# learning_rate = [0.05, 0.1, 0.15, 0.20]
# min_child_weight = [1, 2, 3, 4]
# base_score = [0.25, 0.5, 0.75, 1]
# # define the grid of hyperparameters to search

# hyperparameter_grid = {
#     'n_estimators': n_estimators,
#     'max_depth':max_depth,
#     'learning_rate':learning_rate,
#     'min_child_weight':min_child_weight,
#     'booster':booster,
#     'base_score': base_score
# }

In [382]:
# from sklearn.model_selection import RandomizedSearchCV

In [383]:
# random_cv = RandomizedSearchCV(
#     estimator = xgb,
#     param_distributions= hyperparameter_grid,
#     cv = 5,
#     n_iter = 50,
#     scoring = 'neg_mean_absolute_error',
#     n_jobs=4,
#     verbose = 5,
#     return_train_score = True,
#     random_state = 42
# )

In [384]:
# random_cv.fit(x_train, y_train)

In [385]:
# random_cv.best_estimator_

In [386]:
import numpy as np
import xgboost as xgb

regressor = xgb.XGBRegressor(
    base_score=0.25,
    booster='gbtree',
    colsample_bylevel=1,
    colsample_bytree=1,
    gamma=0,
    learning_rate=0.1,
    max_delta_step=0,
    max_depth=2,
    min_child_weight=1,
    missing=np.nan,  # <-- এখানে np.nan ব্যবহার করতে হবে
    n_estimators=900,
    n_jobs=1,
    objective='reg:squarederror',
    random_state=0,
    reg_alpha=0,
    reg_lambda=1,
    scale_pos_weight=1,
    subsample=1,
    verbosity=0
)

regressor.fit(x_train, y_train)

y_pred = regressor.predict(df_test)
len(y_pred)

1422

In [387]:
from sklearn.metrics import mean_absolute_error
score = mean_absolute_error(y_train, y_pred)
score

81050.93705498418

In [388]:
import pickle
filename = 'finalized_model.pkl'
pickle.dump(regressor, open(filename, 'wb'))

In [389]:
y_pred = regressor.predict(df_test)

In [390]:
y_pred

array([133731.98 , 107915.766, 181144.72 , ..., 119842.11 , 188954.67 ,
       138675.58 ], dtype=float32)

In [391]:
pred = pd.DataFrame(y_pred)
sub_df = pd.read_csv("/content/drive/MyDrive/dataset/sample_submission.csv")
datasets = pd.DataFrame()
datasets["Id"] = sub_df["Id"].astype(int)
datasets["SalePrice"] = pred.iloc[:,0]
datasets.to_csv('/content/sample_data/sample_submission.csv', index=False)

In [392]:
df = pd.read_csv(r"/content/sample_data/sample_submission.csv")
df.head()

     Id   SalePrice
0  1461  133731.980
1  1462  107915.766
2  1463  181144.720
3  1464  173746.030
4  1465  175668.060

In [393]:
df.shape

(1459, 2)

In [394]:
corr = df_train.corr()
corr

                     Id  MSSubClass  LotFrontage   LotArea  OverallQual  \
Id             1.000000    0.013532    -0.013616 -0.032146    -0.030931
MSSubClass     0.013532    1.000000    -0.351318 -0.134172     0.037152
LotFrontage   -0.013616   -0.351318     1.000000  0.306013     0.230690
LotArea       -0.032146   -0.134172     0.306013  1.000000     0.108171
OverallQual   -0.030931    0.037152     0.230690  0.108171     1.000000
OverallCond    0.003890   -0.061323    -0.052506 -0.002282    -0.088319
YearBuilt     -0.020469    0.026320     0.117433  0.016859     0.573889
YearRemodAdd  -0.036558    0.043120     0.080500  0.016685     0.554509
MasVnrArea    -0.048051    0.025179     0.177369  0.103728     0.410117
BsmtFinSF1    -0.002887   -0.072678     0.218371  0.214721     0.235796
BsmtFinSF2    -0.012360   -0.064602     0.044542  0.114558    -0.055808
BsmtUnfSF     -0.007177   -0.131969     0.118731 -0.005976     0.312429
TotalBsmtSF   -0.014712   -0.231563     0.362131  0.258562     0.538260
1stFlrSF       0.010766   -0.245634     0.414089  0.296445     0.478137
2ndFlrSF       0.014406    0.310940     0.072688  0.053221     0.297783
LowQualFinSF  -0.051813    0.046157     0.035900  0.004331    -0.030798
GrLivArea      0.015114    0.082165     0.367479  0.262103     0.595260
BsmtFullBath  -0.004536    0.001675     0.092361  0.161778     0.106538
BsmtHalfBath  -0.011537   -0.002842    -0.005980  0.048257    -0.040087
FullBath       0.005777    0.141006     0.178037  0.123284     0.553592
HalfBath       0.007123    0.179133     0.047796  0.016719     0.276097
BedroomAbvGr   0.050873   -0.014700     0.237314  0.115381     0.107063
KitchenAbvGr   0.007104    0.289338    -0.004054 -0.024659    -0.185640
TotRmsAbvGrd   0.033953    0.048503     0.318377  0.188240     0.428895
Fireplaces    -0.013806   -0.042732     0.234202  0.271951     0.398150
GarageYrBlt   -0.008466    0.093908     0.038873 -0.040328     0.437781
GarageCars     0.022439   -0.035785     0.267297  0.157446     0.599281
GarageArea     0.023426   -0.094909     0.322237  0.183478     0.560207
WoodDeckSF    -0.034335   -0.004902     0.074668  0.173016     0.253140
OpenPorchSF   -0.003506   -0.001691     0.134215  0.086649     0.302981
EnclosedPorch  0.003110   -0.010472     0.008103 -0.022787    -0.116435
3SsnPorch     -0.058475   -0.039823     0.056677  0.019851     0.021994
ScreenPorch    0.010939   -0.026628     0.038555  0.043439     0.066614
PoolArea       0.061623    0.008261     0.182367  0.077983     0.066256
MiscVal       -0.009442   -0.009117     0.002006  0.039059    -0.034186
MoSold         0.014963   -0.015989     0.010454  0.005016     0.065356
YrSold        -0.002353   -0.015078     0.003168 -0.014245    -0.030778
SalePrice     -0.023245   -0.080815     0.331940  0.266420     0.789366
FV            -0.020572    0.180506    -0.093350 -0.084090     0.162687
RH             0.037616    0.058883    -0.043338 -0.033237    -0.065286
RL             0.032496   -0.341132     0.325610  0.201879     0.135583
RM            -0.031395    0.270857    -0.306006 -0.171291    -0.195670
Pave           0.006737   -0.025184    -0.037734 -0.197925     0.059467
IR2           -0.032329   -0.019999     0.032174  0.226134     0.079317
IR3            0.047186   -0.031813     0.182077  0.257569     0.042899
Reg            0.012921    0.128804    -0.170126 -0.215253    -0.206808
HLS            0.024648   -0.011198     0.063956  0.089991     0.105602
Low           -0.010959   -0.029450     0.044633  0.362908    -0.043842
Lvl           -0.021332    0.010437    -0.087071 -0.257973     0.015144
NoSeWa         0.014784   -0.023207     0.000053  0.010162    -0.001836
CulDSac        0.002298   -0.041059    -0.058373  0.171391     0.081104
FR2           -0.004529    0.023304    -0.039415 -0.001012     0.014526
FR3            0.020343    0.044630     0.001786 -0.009553     0.044371
Inside         0.032444    0.063733    -0.150823 -0.129101    -0.048237
Mod            0.033033   -0.017764     0.069222  0.091778    -0.047056
Sev           -0.026950   -0.017608     0.022800  0.542598    -0.044080
Blueste        0.005790    0.091464    -0.077970 -0.033141    -0.002598
BrDale         0.001143    0.259984    -0.233371 -0.092339    -0.031510
BrkSide        0.003720   -0.033317    -0.103131 -0.064599    -0.156844
ClearCr       -0.037678   -0.015019     0.040139  0.286520    -0.020799
CollgCr       -0.005288   -0.114224     0.021382 -0.028781     0.129170
Crawfor        0.029384    0.006907     0.012167  0.017097     0.023698
Edwards        0.017550   -0.006402    -0.016895 -0.006570    -0.196373
Gilbert        0.013140    0.006624     0.066368  0.022848     0.083114
IDOTRR        -0.046375   -0.012880    -0.050880 -0.039091    -0.158374
MeadowV       -0.006861    0.266293    -0.175833 -0.086274    -0.128013
Mitchel       -0.000182    0.008833    -0.004783  0.009876    -0.061557
NAmes          0.010826   -0.184477     0.106481 -0.015232    -0.226356
NPkVill       -0.002664    0.156624    -0.112092 -0.055705    -0.005206
NWAmes         0.049973   -0.066496     0.070576  0.029610     0.037877
NoRidge        0.041919   -0.013537     0.137059  0.063332     0.228346
NridgHt       -0.071136    0.034723     0.119298  0.007254     0.366193
OldTown       -0.023898    0.068852    -0.094279 -0.067230    -0.147250
SWISU          0.040955    0.048167    -0.061628 -0.031750    -0.063475
Sawyer        -0.005017   -0.093441     0.030783 -0.000695    -0.182148
SawyerW       -0.027100    0.009267     0.012546 -0.012216     0.032042
Somerst        0.006355    0.109861    -0.057339 -0.066341     0.215018
StoneBr       -0.014649    0.082979    -0.035253  0.002050     0.199859
Timber         0.022250   -0.071924     0.060087  0.219494     0.132551
Veenker       -0.020485    0.010107    -0.026048  0.044615     0.040361
Feedr          0.038966   -0.039145     0.056079  0.005174    -0.139980
Norm          -0.016520    0.044306    -0.076960 -0.025756     0.099802
PosA          -0.007603   -0.039111     0.153772  0.045525     0.028816
PosN           0.005286   -0.032980     0.028046  0.025600     0.049569
RRAe          -0.020330   -0.025972    -0.028622  0.010488    -0.040966
RRAn           0.022555   -0.008875    -0.021106  0.019853     0.024742
RRNe          -0.032772    0.002682     0.005118 -0.004269     0.010983
RRNn           0.002766   -0.006998     0.031667 -0.008676     0.038878
2fmCon        -0.017864    0.450410    -0.021751  0.078089    -0.125343
Duplex         0.030165    0.150662     0.014512 -0.015005    -0.158406
Twnhs         -0.003920    0.413380    -0.330905 -0.140429    -0.000051
TwnhsE         0.016142    0.521356    -0.298087 -0.164903     0.134266
1.5Unf        -0.075436   -0.001876    -0.066758 -0.033694    -0.044080
1Story        -0.016874   -0.465188     0.062972  0.008957    -0.112404
2.5Fin        -0.036319    0.057320     0.027662  0.014564     0.016947
2.5Unf         0.002033    0.081314    -0.029727 -0.011962     0.028743
2Story        -0.004324    0.354498     0.007082 -0.011350     0.282083
SFoyer         0.017582    0.175090    -0.068425 -0.042436    -0.089827
SLvl           0.032892    0.137459     0.046612  0.002691    -0.024748
Gable         -0.044183    0.131144    -0.176651 -0.109116    -0.162845
Gambrel       -0.021495    0.013904    -0.043520 -0.009501    -0.040966
Hip            0.053226   -0.133650     0.166677  0.083910     0.183840
Mansard       -0.027345    0.012157     0.039460  0.003988    -0.004868
Shed           0.048713    0.007121     0.000076  0.039970    -0.002598
CompShg        0.009043    0.030605    -0.157219 -0.184268    -0.074126
Membran       -0.028430   -0.023207     0.003588  0.075306     0.017362
Metal         -0.038126    0.014447     0.000053  0.028808    -0.001836
Roll           0.036038    0.020722     0.029943  0.002180    -0.021035
Tar&Grv        0.013982   -0.025972     0.100822  0.089566    -0.023539
WdShake       -0.008938   -0.018240     0.025819  0.031147     0.056074
WdShngl       -0.032289   -0.017164     0.032320  0.130395     0.105417
AsphShn        0.019086    0.020722     0.005984 -0.001825    -0.021035
BrkComm       -0.000796   -0.032831     0.001686 -0.002345    -0.056918
BrkFace        0.007781   -0.066763     0.020925  0.082388    -0.021446
CBlock         0.042138   -0.004380     0.023953 -0.013481    -0.040233
CemntBd       -0.005895    0.158164    -0.076080 -0.024227     0.111585
HdBoard        0.013746   -0.009307     0.015767 -0.013128    -0.084544
ImStucc        0.030388   -0.023207     0.022755  0.005120     0.036561
MetalSd        0.034146    0.089800    -0.122600 -0.081263    -0.171089
Plywood       -0.021889    0.049732     0.009942  0.113491    -0.054522
Stone          0.033997   -0.032831     0.016981  0.015984     0.024563
Stucco        -0.002318   -0.008797     0.049312  0.014658    -0.005387
VinylSd       -0.017205   -0.066776     0.075637 -0.042765     0.348462
Wd Sdng       -0.021212   -0.063613     0.030903  0.045890    -0.152081
WdShing       -0.008103   -0.036193    -0.031785 -0.001280    -0.043634
Brk Cmn       -0.002197    0.104859    -0.103474 -0.042288    -0.033955
CmentBd       -0.001146    0.159276    -0.069831 -0.040353     0.118085
Other         -0.007626   -0.023207    -0.001204  0.002066     0.036561
Wd Shng        0.007168    0.029892    -0.066550 -0.007673    -0.002002
Fa             0.000437    0.027345     0.013501 -0.021719    -0.166696
Gd             0.026660    0.053348     0.085457  0.003910     0.554566
TA            -0.012599   -0.048023    -0.141317 -0.028464    -0.645588
Po            -0.029779   -0.016931    -0.017976 -0.013613    -0.059432
PConc         -0.006952    0.073754     0.055321 -0.034133     0.571186
Slab           0.021220    0.019048    -0.022406 -0.018215    -0.171060
Wood           0.009450   -0.003966     0.067162  0.008928     0.019002
Mn             0.030230    0.005616     0.032941  0.005730     0.036115
No            -0.032481   -0.050299    -0.148816 -0.179782    -0.252405
BLQ            0.040006   -0.072185    -0.003744  0.012119    -0.182311
GLQ           -0.025464    0.089744     0.086306  0.019111     0.432358
LwQ           -0.032241   -0.013850    -0.058923 -0.019660    -0.094909
Rec            0.009691   -0.090851     0.031549  0.026663    -0.171633
Unf            0.016283    0.038678    -0.053414 -0.067515    -0.020017
GasA          -0.037446   -0.052249     0.005234 -0.082059     0.114887
GasW           0.003446    0.047525     0.010483  0.128442    -0.039704
Grav           0.012380    0.013634     0.004394 -0.015696    -0.098725
OthW           0.053119    0.013779    -0.025431 -0.011526     0.024563
Wall           0.023718    0.028924    -0.023968 -0.012365    -0.099770
Y              0.010043   -0.106042     0.069391  0.050401     0.273570
FuseF         -0.027707   -0.003908    -0.029414 -0.028785    -0.138602
FuseP         -0.059072    0.050421    -0.031850 -0.016953    -0.036459
Mix           -0.020276   -0.016931    -0.011986 -0.004085    -0.021035
SBrkr          0.047722    0.042563     0.066099  0.045712     0.262898
Maj2          -0.010922   -0.035103    -0.001624 -0.009734    -0.047101
Min1          -0.035190   -0.037948    -0.025571  0.028565    -0.092804
Min2           0.034968   -0.014401     0.004244  0.010016    -0.122219
Typ            0.000325    0.010612     0.026038 -0.029365     0.174812
Attchd        -0.012172   -0.116206     0.173130  0.090482     0.237503
Basment        0.037401    0.024460     0.052867  0.003280    -0.021495
BuiltIn       -0.007736    0.077103     0.078290  0.039133     0.206622
CarPort       -0.015022    0.039267     0.021625  0.009168    -0.101788
Detchd         0.010741    0.065390    -0.245507 -0.127452    -0.336057
RFn            0.005559   -0.045154     0.131206  0.014303     0.218258
P              0.002925   -0.015048    -0.015357  0.002613    -0.073023
CWD            0.023943    0.028924    -0.006009 -0.007854     0.034762
Con           -0.015421    0.029316    -0.030516 -0.002887     0.038143
ConLD         -0.001520    0.086468     0.033639 -0.006049    -0.037612
ConLI         -0.058486   -0.001377     0.012889  0.001076     0.004486
ConLw         -0.019175    0.014081    -0.052056 -0.015106    -0.021307
New           -0.023706   -0.042174     0.123711  0.020781     0.321916
Oth            0.041986   -0.014844    -0.023544 -0.005748    -0.058643
WD             0.028418    0.021915    -0.086143 -0.002967    -0.218537
AdjLand       -0.034005    0.016360    -0.037190 -0.013265    -0.042114
Alloca        -0.002474    0.038590    -0.018853 -0.008263    -0.046775
Family         0.009581    0.000764     0.016179 -0.010835    -0.025555
Normal         0.018467    0.022874    -0.071305  0.008910    -0.139467
Partial       -0.025200   -0.048332     0.121950  0.023426     0.317707

               OverallCond  YearBuilt  YearRemodAdd  MasVnrArea  BsmtFinSF1  \
Id                0.003890  -0.020469     -0.036558   -0.048051   -0.002887
MSSubClass       -0.061323   0.026320      0.043120    0.025179   -0.072678
LotFrontage      -0.052506   0.117433      0.080500    0.177369    0.218371
LotArea          -0.002282   0.016859      0.016685    0.103728    0.214721
OverallQual      -0.088319   0.573889      0.554509    0.410117    0.235796
OverallCond       1.000000  -0.372291      0.076386   -0.127411   -0.039485
YearBuilt        -0.372291   1.000000      0.594095    0.314789    0.248969
YearRemodAdd      0.076386   0.594095      1.000000    0.179215    0.132880
MasVnrArea       -0.127411   0.314789      0.179215    1.000000    0.263078
BsmtFinSF1       -0.039485   0.248969      0.132880    0.263078    1.000000
BsmtFinSF2        0.040914  -0.044860     -0.065360   -0.069954   -0.047489
BsmtUnfSF        -0.141864   0.151553      0.179687    0.113919   -0.495327
TotalBsmtSF      -0.168601   0.394277      0.294609    0.361957    0.522685
1stFlrSF         -0.142668   0.287003      0.242796    0.343021    0.445754
2ndFlrSF          0.027706   0.010550      0.140298    0.174870   -0.135441
LowQualFinSF      0.019463  -0.180162     -0.065621   -0.068013   -0.061160
GrLivArea        -0.079896   0.202844      0.288629    0.390655    0.209015
BsmtFullBath     -0.051053   0.184081      0.117897    0.081971    0.650616
BsmtHalfBath      0.120024  -0.036804     -0.009826    0.026262    0.068566
FullBath         -0.188794   0.472817      0.442138    0.277615    0.055848
HalfBath         -0.060805   0.243760      0.184623    0.202420    0.005726
BedroomAbvGr      0.014311  -0.067739     -0.038700    0.104030   -0.103039
KitchenAbvGr     -0.079936  -0.176666     -0.147749   -0.036742   -0.085259
TotRmsAbvGrd     -0.058915   0.098708      0.191804    0.281170    0.047507
Fireplaces       -0.023927   0.152911      0.114524    0.247052    0.260000
GarageYrBlt      -0.293280   0.695638      0.573944    0.211736    0.117432
GarageCars       -0.182783   0.540285      0.421562    0.362345    0.219529
GarageArea       -0.151208   0.483687      0.372276    0.372563    0.294835
WoodDeckSF       -0.007010   0.239651      0.217806    0.167728    0.207843
OpenPorchSF      -0.031876   0.187316      0.227173    0.126535    0.106438
EnclosedPorch     0.076209  -0.392921     -0.192317   -0.109429   -0.105926
3SsnPorch         0.030942   0.024779      0.040405    0.006109    0.013305
ScreenPorch       0.055975  -0.048051     -0.035381    0.061487    0.063625
PoolArea         -0.001874   0.005553      0.006646    0.011623    0.142341
MiscVal           0.059628  -0.030933     -0.013154   -0.028418    0.005038
MoSold           -0.001482   0.005544      0.016431   -0.009212   -0.017814
YrSold            0.037408  -0.011526      0.035615   -0.008493    0.017003
SalePrice        -0.075630   0.525390      0.510005    0.475355    0.383598
FV               -0.105047   0.231566      0.202929    0.044672   -0.057956
RH               -0.001021  -0.089544     -0.065485   -0.027143   -0.030497
RL               -0.072952   0.284449      0.082655    0.092071    0.214593
RM                0.159822  -0.397791     -0.163965   -0.110917   -0.193786
Pave              0.043313   0.020913      0.065451    0.017569   -0.015906
IR2              -0.001885   0.081219      0.094775    0.020963    0.009428
IR3              -0.058518   0.046724      0.045377   -0.011335    0.123753
Reg               0.018568  -0.246152     -0.176868   -0.103138   -0.145824
HLS              -0.002255   0.051875      0.049800    0.017786    0.030761
Low              -0.032901  -0.006795     -0.008651   -0.031848    0.126623
Lvl              -0.022331   0.114823      0.064991    0.044938   -0.065210
NoSeWa            0.010185  -0.011451     -0.034151    0.063698   -0.019314
CulDSac           0.018696   0.118513      0.092968    0.051788    0.085876
FR2              -0.017156   0.068340      0.052074    0.005109    0.020479
FR3               0.008449   0.018847      0.043908    0.000990    0.024571
Inside           -0.032571  -0.019728     -0.036688   -0.034683   -0.039208
Mod               0.021186  -0.056269     -0.044325   -0.013914    0.096941
Sev              -0.009641  -0.040973     -0.036538   -0.013742    0.064579
Blueste           0.014408   0.011143     -0.008417   -0.021473   -0.021402
BrDale           -0.013014   0.001424     -0.056786    0.119284   -0.045066
BrkSide           0.104249  -0.266174     -0.155315   -0.108470   -0.109289
ClearCr           0.013440  -0.020947     -0.006104   -0.015217    0.055203
CollgCr          -0.099350   0.299764      0.235927   -0.016639    0.006111
Crawfor           0.173321  -0.181906     -0.056219   -0.018408    0.008878
Edwards          -0.036613  -0.136098     -0.130636   -0.078667   -0.011736
Gilbert          -0.094368   0.213541      0.161998   -0.085063   -0.119232
IDOTRR           -0.004792  -0.233227     -0.160036   -0.078953   -0.107432
MeadowV          -0.013014   0.006061     -0.038745   -0.058106   -0.014524
Mitchel          -0.037051   0.064948      0.010275   -0.043122    0.082812
NAmes             0.079147  -0.157910     -0.275446   -0.005204    0.045325
NPkVill          -0.004948   0.013614     -0.029591   -0.043038   -0.010416
NWAmes            0.076396   0.034276     -0.035188    0.095034    0.033213
NoRidge          -0.054801   0.139254      0.100055    0.299168    0.145993
NridgHt          -0.121635   0.270417      0.245207    0.296393    0.121997
OldTown           0.203663  -0.467292     -0.136195   -0.143381   -0.179869
SWISU             0.041733  -0.202874     -0.096712   -0.069131   -0.068805
Sawyer            0.052051  -0.056935     -0.066801   -0.079913    0.035542
SawyerW          -0.077517   0.117975      0.050990   -0.036252    0.043112
Somerst          -0.120368   0.273519      0.241961    0.071211   -0.064195
StoneBr          -0.068958   0.121586      0.091782    0.057827    0.111342
Timber           -0.064388   0.116114      0.065803    0.054044    0.101909
Veenker           0.055556   0.033126      0.022087   -0.034638    0.072906
Feedr             0.037048  -0.136432     -0.108782   -0.020924    0.014779
Norm             -0.083765   0.195399      0.131509    0.039799    0.015022
PosA              0.062703  -0.006625      0.021748    0.014424    0.017693
PosN              0.011626   0.004127     -0.003902    0.060220    0.058833
RRAe              0.005021   0.025152      0.013166   -0.022948    0.025510
RRAn             -0.004256   0.013576      0.034577   -0.047046   -0.032083
RRNe              0.014408   0.027299      0.024225   -0.009098   -0.002400
RRNn              0.001435   0.015276      0.028585    0.032612   -0.003122
2fmCon            0.022664  -0.207649     -0.098172   -0.072978   -0.001252
Duplex           -0.113026  -0.025518     -0.134627    0.009613   -0.012204
Twnhs            -0.022683   0.090587      0.040356    0.053590   -0.043633
TwnhsE           -0.137422   0.238870      0.161852    0.032510    0.025628
1.5Unf            0.050168  -0.114869     -0.100805   -0.054960   -0.059506

In [395]:
# Boolean mask: শুরুতে সব কলামকে True ধরা
columns = np.ones(corr.shape[0], dtype=bool)

# Highly correlated কলাম বাদ দেওয়া
for i in range(corr.shape[0]):
    for j in range(i + 1, corr.shape[0]):
        if corr.iloc[i, j] >= 0.9:   # যদি correlation ≥ 0.9 হয়
            columns[j] = False       # দ্বিতীয় কলামটি বাদ দাও

# Only selected columns
selected_columns = df_train.columns[columns]
data = df_train[selected_columns]

In [396]:
import numpy as np
import seaborn as sb

In [397]:
# num_true = np.sum(columns)
# num_false = np.sum(~columns)
# num_false

In [398]:
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from scipy import stats
import warnings
warnings.filterwarnings('ignore')
%matplotlib

Using matplotlib backend: agg

In [399]:
df = main_df
df.head(4)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,0,2,2006,WD,Abnorml,140000

In [400]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrArea', 'ExterQual',
       'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
       'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF',
       'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical',
       '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath',
       'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr',
       'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice'],
      dtype='object')

In [401]:
df['SalePrice'].describe()

count      1451.000000
mean     180624.101999
std       79312.128273
min       34900.000000
25%      129900.000000
50%      162500.000000
75%      214000.000000
max      755000.000000
Name: SalePrice, dtype: float64

In [402]:
sb.distplot(df['SalePrice'])
# sb.histplot(df['SalePrice'], kde=True, bins=50)
# plt.show()

In [403]:
#skewness and kurtosis
df['SalePrice'].skew()

np.float64(1.8831110462405252)

In [404]:
df['SalePrice'].kurt()

np.float64(6.573025006423077)

In [405]:
# df['GrLivArea']

In [406]:
# Relationship with numerical variables

var = 'GrLivArea'
data = pd.concat([df['SalePrice'], df[[var]]], axis = 1)
data.plot.scatter(x = var, y = 'SalePrice', ylim = (0,800000))

In [407]:
# Relationship with numerical variables

var = 'TotalBsmtSF'
data = pd.concat([df['SalePrice'], df[[var]]], axis = 1)
data.plot.scatter(x = var, y = 'SalePrice', ylim = (0,800000))

In [408]:
# Relationship with categorical features

var = 'OverallQual'
data = pd.concat([df['SalePrice'], df_train[var]], axis = 1)
f, ax = plt.subplots(figsize = (8,6))
fig = sb.boxplot(x = var, y = 'SalePrice', data = data)
fig.axis(ymin = 0, ymax = 800000)

(np.float64(-0.5), np.float64(9.5), np.float64(0.0), np.float64(800000.0))

In [409]:
# Relationship with categorical features

var = 'YearBuilt'
data = pd.concat([df['SalePrice'], df_train[var]], axis = 1)
f, ax = plt.subplots(figsize = (8,6))
fig = sb.boxplot(x = var, y = 'SalePrice', data = data)
fig.axis(ymin = 0, ymax = 800000)
plt.xticks(rotation = 90)

([0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111],
 [Text(0, 0, '1872.0'),
  Text(1, 0, '1875.0'),
  Text(2, 0, '1880.0'),
  Text(3, 0, '1882.0'),
  Text(4, 0, '1885.0'),
  Text(5, 0, '1890.0'),
  Text(6, 0, '1892.0'),
  Text(7, 0, '1893.0'),
  Text(8, 0, '1898.0'),
  Text(9, 0, '1900.0'),
  Text(10, 0, '1904.0'),
  Text(11, 0, '1905.0'),
  Text(12, 0, '1906.0'),
  Text(13, 0, '1908.0'),
  Text(14, 0, '1910.0'),
  Text(15, 0, '1911.0'),
  Text(16, 0, '1912.0'),
  Text(17, 0, '1913.0'),
  Text(18, 0, '1914.0'),
  Text(19, 0, '1915.0'),
  Text(20, 0, '1916.0'),
  Text(21, 0, '1917.0'),
  Text(22, 0, '1918.0'),
  Text(23, 0, '1919.0'),
  Text(24, 0, '1920.0'),
  Text(25, 0, '1921.0'),
  Text(26, 0, '1922.0'),
  Text(27, 0, '1923.0'),
  Text(28, 0, '1924.0'),
  Text(29, 0, '1925.0'),
  Text(30, 0, '1926.0'),
  Text(31, 0, '1927.0'),
  Text(32, 0, '1928.0'),
  Text(33, 0, '1929.0'),
  Text(34, 0, '1930.0'),
  Text(35, 0, '1931.0'),
  Text(36, 0, '1932.0'),
  Text(37, 0, '1934.0'),
  Text(38, 0, '1935.0'),
  Text(39, 0, '1936.0'),
  Text(40, 0, '1937.0'),
  Text(41, 0, '1938.0'),
  Text(42, 0, '1939.0'),
  Text(43, 0, '1940.0'),
  Text(44, 0, '1941.0'),
  Text(45, 0, '1942.0'),
  Text(46, 0, '1945.0'),
  Text(47, 0, '1946.0'),
  Text(48, 0, '1947.0'),
  Text(49, 0, '1948.0'),
  Text(50, 0, '1949.0'),
  Text(51, 0, '1950.0'),
  Text(52, 0, '1951.0'),
  Text(53, 0, '1952.0'),
  Text(54, 0, '1953.0'),
  Text(55, 0, '1954.0'),
  Text(56, 0, '1955.0'),
  Text(57, 0, '1956.0'),
  Text(58, 0, '1957.0'),
  Text(59, 0, '1958.0'),
  Text(60, 0, '1959.0'),
  Text(61, 0, '1960.0'),
  Text(62, 0, '1961.0'),
  Text(63, 0, '1962.0'),
  Text(64, 0, '1963.0'),
  Text(65, 0, '1964.0'),
  Text(66, 0, '1965.0'),
  Text(67, 0, '1966.0'),
  Text(68, 0, '1967.0'),
  Text(69, 0, '1968.0'),
  Text(70, 0, '1969.0'),
  Text(71, 0, '1970.0'),
  Text(72, 0, '1971.0'),
  Text(73, 0, '1972.0'),
  Text(74, 0, '1973.0'),
  Text(75, 0, '1974.0'),
  Text(76, 0, '1975.0'),
  Text(77, 0, '1976.0'),
  Text(78, 0, '1977.0'),
  Text(79, 0, '1978.0'),
  Text(80, 0, '1979.0'),
  Text(81, 0, '1980.0'),
  Text(82, 0, '1981.0'),
  Text(83, 0, '1982.0'),
  Text(84, 0, '1983.0'),
  Text(85, 0, '1984.0'),
  Text(86, 0, '1985.0'),
  Text(87, 0, '1986.0'),
  Text(88, 0, '1987.0'),
  Text(89, 0, '1988.0'),
  Text(90, 0, '1989.0'),
  Text(91, 0, '1990.0'),
  Text(92, 0, '1991.0'),
  Text(93, 0, '1992.0'),
  Text(94, 0, '1993.0'),
  Text(95, 0, '1994.0'),
  Text(96, 0, '1995.0'),
  Text(97, 0, '1996.0'),
  Text(98, 0, '1997.0'),
  Text(99, 0, '1998.0'),
  Text(100, 0, '1999.0'),
  Text(101, 0, '2000.0'),
  Text(102, 0, '2001.0'),
  Text(103, 0, '2002.0'),
  Text(104, 0, '2003.0'),
  Text(105, 0, '2004.0'),
  Text(106, 0, '2005.0'),
  Text(107, 0, '2006.0'),
  Text(108, 0, '2007.0'),
  Text(109, 0, '2008.0'),
  Text(110, 0, '2009.0'),
  Text(111, 0, '2010.0')])

In [419]:
corrmat = df.corr(numeric_only=True)

f, ax = plt.subplots(figsize=(12, 9))
sb.heatmap(corrmat, vmax=0.8, square=True)
plt.show()

In [420]:
sb.set()
cols = ['SalePrice', 'OverallQual', 'GrLivArea', 'GarageCars', 'TotalBsmtSF', 'FullBath', 'YearBuilt']
sb.pairplot(df[cols], size = 2.5)
plt.show();